package com.lanqiao.model;

public class LQCity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lq_city.city_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lq_city.pid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lq_city.city
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lq_city.f_letter
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String fLetter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lq_city.city_id
     *
     * @return the value of lq_city.city_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lq_city.city_id
     *
     * @param cityId the value for lq_city.city_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lq_city.pid
     *
     * @return the value of lq_city.pid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lq_city.pid
     *
     * @param pid the value for lq_city.pid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lq_city.city
     *
     * @return the value of lq_city.city
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lq_city.city
     *
     * @param city the value for lq_city.city
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lq_city.f_letter
     *
     * @return the value of lq_city.f_letter
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getfLetter() {
        return fLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lq_city.f_letter
     *
     * @param fLetter the value for lq_city.f_letter
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setfLetter(String fLetter) {
        this.fLetter = fLetter;
    }
}