package com.lanqiao.model;

public class LQUniversities {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lq_universities.univ_code
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    private Long univCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lq_universities.univ_name
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    private String univName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lq_universities.univ_introduction
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    private String univIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lq_universities.univ_pinyin
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    private String univPinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lq_universities.isvalid
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    private Integer isvalid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lq_universities.univ_code
     *
     * @return the value of lq_universities.univ_code
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    public Long getUnivCode() {
        return univCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lq_universities.univ_code
     *
     * @param univCode the value for lq_universities.univ_code
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    public void setUnivCode(Long univCode) {
        this.univCode = univCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lq_universities.univ_name
     *
     * @return the value of lq_universities.univ_name
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    public String getUnivName() {
        return univName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lq_universities.univ_name
     *
     * @param univName the value for lq_universities.univ_name
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    public void setUnivName(String univName) {
        this.univName = univName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lq_universities.univ_introduction
     *
     * @return the value of lq_universities.univ_introduction
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    public String getUnivIntroduction() {
        return univIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lq_universities.univ_introduction
     *
     * @param univIntroduction the value for lq_universities.univ_introduction
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    public void setUnivIntroduction(String univIntroduction) {
        this.univIntroduction = univIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lq_universities.univ_pinyin
     *
     * @return the value of lq_universities.univ_pinyin
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    public String getUnivPinyin() {
        return univPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lq_universities.univ_pinyin
     *
     * @param univPinyin the value for lq_universities.univ_pinyin
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    public void setUnivPinyin(String univPinyin) {
        this.univPinyin = univPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lq_universities.isvalid
     *
     * @return the value of lq_universities.isvalid
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lq_universities.isvalid
     *
     * @param isvalid the value for lq_universities.isvalid
     *
     * @mbggenerated Thu Mar 16 16:17:43 CST 2017
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }
}