package com.lanqiao.model;

import java.util.Date;

public class StudentSign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_sign.sign_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer signId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_sign.sutdent_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer sutdentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_sign.ca_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer caId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_sign.create_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_sign.type
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_sign.Leave_reason
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private String leaveReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_sign.sign_id
     *
     * @return the value of t_student_sign.sign_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getSignId() {
        return signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_sign.sign_id
     *
     * @param signId the value for t_student_sign.sign_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setSignId(Integer signId) {
        this.signId = signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_sign.sutdent_id
     *
     * @return the value of t_student_sign.sutdent_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getSutdentId() {
        return sutdentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_sign.sutdent_id
     *
     * @param sutdentId the value for t_student_sign.sutdent_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setSutdentId(Integer sutdentId) {
        this.sutdentId = sutdentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_sign.ca_id
     *
     * @return the value of t_student_sign.ca_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getCaId() {
        return caId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_sign.ca_id
     *
     * @param caId the value for t_student_sign.ca_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setCaId(Integer caId) {
        this.caId = caId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_sign.create_time
     *
     * @return the value of t_student_sign.create_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_sign.create_time
     *
     * @param createTime the value for t_student_sign.create_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_sign.type
     *
     * @return the value of t_student_sign.type
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_sign.type
     *
     * @param type the value for t_student_sign.type
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_sign.Leave_reason
     *
     * @return the value of t_student_sign.Leave_reason
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public String getLeaveReason() {
        return leaveReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_sign.Leave_reason
     *
     * @param leaveReason the value for t_student_sign.Leave_reason
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setLeaveReason(String leaveReason) {
        this.leaveReason = leaveReason;
    }
}