package com.lanqiao.model;

import java.util.Date;

public class StudentWeelyevaluate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weelyevaluate.nnid
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer nnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weelyevaluate.we_evaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer weEvaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weelyevaluate.evaluate_content
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private String evaluateContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weelyevaluate.createe_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Date createeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weelyevaluate.student_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weelyevaluate.teacher_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weelyevaluate.weekiy_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer weekiyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weelyevaluate.nnid
     *
     * @return the value of t_student_weelyevaluate.nnid
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getNnid() {
        return nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weelyevaluate.nnid
     *
     * @param nnid the value for t_student_weelyevaluate.nnid
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setNnid(Integer nnid) {
        this.nnid = nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weelyevaluate.we_evaluate
     *
     * @return the value of t_student_weelyevaluate.we_evaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getWeEvaluate() {
        return weEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weelyevaluate.we_evaluate
     *
     * @param weEvaluate the value for t_student_weelyevaluate.we_evaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setWeEvaluate(Integer weEvaluate) {
        this.weEvaluate = weEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weelyevaluate.evaluate_content
     *
     * @return the value of t_student_weelyevaluate.evaluate_content
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public String getEvaluateContent() {
        return evaluateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weelyevaluate.evaluate_content
     *
     * @param evaluateContent the value for t_student_weelyevaluate.evaluate_content
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setEvaluateContent(String evaluateContent) {
        this.evaluateContent = evaluateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weelyevaluate.createe_time
     *
     * @return the value of t_student_weelyevaluate.createe_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Date getCreateeTime() {
        return createeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weelyevaluate.createe_time
     *
     * @param createeTime the value for t_student_weelyevaluate.createe_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setCreateeTime(Date createeTime) {
        this.createeTime = createeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weelyevaluate.student_id
     *
     * @return the value of t_student_weelyevaluate.student_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weelyevaluate.student_id
     *
     * @param studentId the value for t_student_weelyevaluate.student_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weelyevaluate.teacher_id
     *
     * @return the value of t_student_weelyevaluate.teacher_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weelyevaluate.teacher_id
     *
     * @param teacherId the value for t_student_weelyevaluate.teacher_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weelyevaluate.weekiy_id
     *
     * @return the value of t_student_weelyevaluate.weekiy_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getWeekiyId() {
        return weekiyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weelyevaluate.weekiy_id
     *
     * @param weekiyId the value for t_student_weelyevaluate.weekiy_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setWeekiyId(Integer weekiyId) {
        this.weekiyId = weekiyId;
    }
}