package com.lanqiao.model;

import java.util.Date;

public class StudentDailyTalk {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_daily_talk.dt_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    private Integer dtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_daily_talk.dt_time
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    private Date dtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_daily_talk.student_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_daily_talk.dt_content
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    private String dtContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_daily_talk.dt_type
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    private Integer dtType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_daily_talk.evaluation
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    private String evaluation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_daily_talk.create_teacher_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    private Integer createTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_daily_talk.create_time
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_daily_talk.class_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_daily_talk.teacher_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    private Integer teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_daily_talk.dt_id
     *
     * @return the value of t_student_daily_talk.dt_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public Integer getDtId() {
        return dtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_daily_talk.dt_id
     *
     * @param dtId the value for t_student_daily_talk.dt_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public void setDtId(Integer dtId) {
        this.dtId = dtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_daily_talk.dt_time
     *
     * @return the value of t_student_daily_talk.dt_time
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public Date getDtTime() {
        return dtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_daily_talk.dt_time
     *
     * @param dtTime the value for t_student_daily_talk.dt_time
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public void setDtTime(Date dtTime) {
        this.dtTime = dtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_daily_talk.student_id
     *
     * @return the value of t_student_daily_talk.student_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_daily_talk.student_id
     *
     * @param studentId the value for t_student_daily_talk.student_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_daily_talk.dt_content
     *
     * @return the value of t_student_daily_talk.dt_content
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public String getDtContent() {
        return dtContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_daily_talk.dt_content
     *
     * @param dtContent the value for t_student_daily_talk.dt_content
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public void setDtContent(String dtContent) {
        this.dtContent = dtContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_daily_talk.dt_type
     *
     * @return the value of t_student_daily_talk.dt_type
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public Integer getDtType() {
        return dtType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_daily_talk.dt_type
     *
     * @param dtType the value for t_student_daily_talk.dt_type
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public void setDtType(Integer dtType) {
        this.dtType = dtType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_daily_talk.evaluation
     *
     * @return the value of t_student_daily_talk.evaluation
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public String getEvaluation() {
        return evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_daily_talk.evaluation
     *
     * @param evaluation the value for t_student_daily_talk.evaluation
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_daily_talk.create_teacher_id
     *
     * @return the value of t_student_daily_talk.create_teacher_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public Integer getCreateTeacherId() {
        return createTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_daily_talk.create_teacher_id
     *
     * @param createTeacherId the value for t_student_daily_talk.create_teacher_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public void setCreateTeacherId(Integer createTeacherId) {
        this.createTeacherId = createTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_daily_talk.create_time
     *
     * @return the value of t_student_daily_talk.create_time
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_daily_talk.create_time
     *
     * @param createTime the value for t_student_daily_talk.create_time
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_daily_talk.class_id
     *
     * @return the value of t_student_daily_talk.class_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_daily_talk.class_id
     *
     * @param classId the value for t_student_daily_talk.class_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_daily_talk.teacher_id
     *
     * @return the value of t_student_daily_talk.teacher_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_daily_talk.teacher_id
     *
     * @param teacherId the value for t_student_daily_talk.teacher_id
     *
     * @mbggenerated Mon Jul 03 11:43:42 CST 2017
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
}