package com.lanqiao.model;

public class StudentWeekly {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weekly.weekiy_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer weekiyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weekly.summarize
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private String summarize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weekly.problem
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private String problem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weekly.solve_problem
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private String solveProblem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weekly.next_week_plans
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private String nextWeekPlans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weekly.student_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_weekly.class_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer classId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weekly.weekiy_id
     *
     * @return the value of t_student_weekly.weekiy_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getWeekiyId() {
        return weekiyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weekly.weekiy_id
     *
     * @param weekiyId the value for t_student_weekly.weekiy_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setWeekiyId(Integer weekiyId) {
        this.weekiyId = weekiyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weekly.summarize
     *
     * @return the value of t_student_weekly.summarize
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public String getSummarize() {
        return summarize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weekly.summarize
     *
     * @param summarize the value for t_student_weekly.summarize
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setSummarize(String summarize) {
        this.summarize = summarize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weekly.problem
     *
     * @return the value of t_student_weekly.problem
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weekly.problem
     *
     * @param problem the value for t_student_weekly.problem
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setProblem(String problem) {
        this.problem = problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weekly.solve_problem
     *
     * @return the value of t_student_weekly.solve_problem
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public String getSolveProblem() {
        return solveProblem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weekly.solve_problem
     *
     * @param solveProblem the value for t_student_weekly.solve_problem
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setSolveProblem(String solveProblem) {
        this.solveProblem = solveProblem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weekly.next_week_plans
     *
     * @return the value of t_student_weekly.next_week_plans
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public String getNextWeekPlans() {
        return nextWeekPlans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weekly.next_week_plans
     *
     * @param nextWeekPlans the value for t_student_weekly.next_week_plans
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setNextWeekPlans(String nextWeekPlans) {
        this.nextWeekPlans = nextWeekPlans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weekly.student_id
     *
     * @return the value of t_student_weekly.student_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weekly.student_id
     *
     * @param studentId the value for t_student_weekly.student_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_weekly.class_id
     *
     * @return the value of t_student_weekly.class_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_weekly.class_id
     *
     * @param classId the value for t_student_weekly.class_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
}