package com.lanqiao.model;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.user_id
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_no
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String stuNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.job_city_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String jobCityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.address
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.univ_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer univCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.school_type_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer schoolTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.school_prov_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer schoolProvCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.school_city_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer schoolCityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.school_dormitory
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String schoolDormitory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.major
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.school_tel
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String schoolTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.school_linkman
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String schoolLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.inv_teacher_id
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer invTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.parent_tel
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String parentTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.parent_info
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String parentInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.update_time
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.create_time
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.grade
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.status
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.course_type
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String courseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.lq_class_id
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer lqClassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.emp_time
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Date empTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.audit_status
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.is_avaiable
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer isAvaiable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.idcard_front_img
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String idcardFrontImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.idcard_back_img
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String idcardBackImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.has_paid
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer hasPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.teacherid_inspector
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer teacheridInspector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.teacherid_advisor
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer teacheridAdvisor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.begin_studytime
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Date beginStudytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.end_studytime
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Date endStudytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.audit_through_time
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Date auditThroughTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.school_duty
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String schoolDuty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.school_subname
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private String schoolSubname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.jobservice_endtime
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Date jobserviceEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.jobservice_starttime
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Date jobserviceStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.jobstatus
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer jobstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.jobfromtype
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    private Integer jobfromtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.user_id
     *
     * @return the value of t_student.user_id
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.user_id
     *
     * @param userId the value for t_student.user_id
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_no
     *
     * @return the value of t_student.stu_no
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getStuNo() {
        return stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_no
     *
     * @param stuNo the value for t_student.stu_no
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setStuNo(String stuNo) {
        this.stuNo = stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.job_city_code
     *
     * @return the value of t_student.job_city_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getJobCityCode() {
        return jobCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.job_city_code
     *
     * @param jobCityCode the value for t_student.job_city_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setJobCityCode(String jobCityCode) {
        this.jobCityCode = jobCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.address
     *
     * @return the value of t_student.address
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.address
     *
     * @param address the value for t_student.address
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.univ_code
     *
     * @return the value of t_student.univ_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getUnivCode() {
        return univCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.univ_code
     *
     * @param univCode the value for t_student.univ_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setUnivCode(Integer univCode) {
        this.univCode = univCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.school_type_code
     *
     * @return the value of t_student.school_type_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getSchoolTypeCode() {
        return schoolTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.school_type_code
     *
     * @param schoolTypeCode the value for t_student.school_type_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setSchoolTypeCode(Integer schoolTypeCode) {
        this.schoolTypeCode = schoolTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.school_prov_code
     *
     * @return the value of t_student.school_prov_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getSchoolProvCode() {
        return schoolProvCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.school_prov_code
     *
     * @param schoolProvCode the value for t_student.school_prov_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setSchoolProvCode(Integer schoolProvCode) {
        this.schoolProvCode = schoolProvCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.school_city_code
     *
     * @return the value of t_student.school_city_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getSchoolCityCode() {
        return schoolCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.school_city_code
     *
     * @param schoolCityCode the value for t_student.school_city_code
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setSchoolCityCode(Integer schoolCityCode) {
        this.schoolCityCode = schoolCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.school_dormitory
     *
     * @return the value of t_student.school_dormitory
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getSchoolDormitory() {
        return schoolDormitory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.school_dormitory
     *
     * @param schoolDormitory the value for t_student.school_dormitory
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setSchoolDormitory(String schoolDormitory) {
        this.schoolDormitory = schoolDormitory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.major
     *
     * @return the value of t_student.major
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.major
     *
     * @param major the value for t_student.major
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.school_tel
     *
     * @return the value of t_student.school_tel
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getSchoolTel() {
        return schoolTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.school_tel
     *
     * @param schoolTel the value for t_student.school_tel
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setSchoolTel(String schoolTel) {
        this.schoolTel = schoolTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.school_linkman
     *
     * @return the value of t_student.school_linkman
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getSchoolLinkman() {
        return schoolLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.school_linkman
     *
     * @param schoolLinkman the value for t_student.school_linkman
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setSchoolLinkman(String schoolLinkman) {
        this.schoolLinkman = schoolLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.inv_teacher_id
     *
     * @return the value of t_student.inv_teacher_id
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getInvTeacherId() {
        return invTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.inv_teacher_id
     *
     * @param invTeacherId the value for t_student.inv_teacher_id
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setInvTeacherId(Integer invTeacherId) {
        this.invTeacherId = invTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.parent_tel
     *
     * @return the value of t_student.parent_tel
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getParentTel() {
        return parentTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.parent_tel
     *
     * @param parentTel the value for t_student.parent_tel
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setParentTel(String parentTel) {
        this.parentTel = parentTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.parent_info
     *
     * @return the value of t_student.parent_info
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getParentInfo() {
        return parentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.parent_info
     *
     * @param parentInfo the value for t_student.parent_info
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setParentInfo(String parentInfo) {
        this.parentInfo = parentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.update_time
     *
     * @return the value of t_student.update_time
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.update_time
     *
     * @param updateTime the value for t_student.update_time
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.create_time
     *
     * @return the value of t_student.create_time
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.create_time
     *
     * @param createTime the value for t_student.create_time
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.grade
     *
     * @return the value of t_student.grade
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.grade
     *
     * @param grade the value for t_student.grade
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.status
     *
     * @return the value of t_student.status
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.status
     *
     * @param status the value for t_student.status
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.course_type
     *
     * @return the value of t_student.course_type
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.course_type
     *
     * @param courseType the value for t_student.course_type
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setCourseType(String courseType) {
        this.courseType = courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.lq_class_id
     *
     * @return the value of t_student.lq_class_id
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getLqClassId() {
        return lqClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.lq_class_id
     *
     * @param lqClassId the value for t_student.lq_class_id
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setLqClassId(Integer lqClassId) {
        this.lqClassId = lqClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.emp_time
     *
     * @return the value of t_student.emp_time
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Date getEmpTime() {
        return empTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.emp_time
     *
     * @param empTime the value for t_student.emp_time
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setEmpTime(Date empTime) {
        this.empTime = empTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.audit_status
     *
     * @return the value of t_student.audit_status
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.audit_status
     *
     * @param auditStatus the value for t_student.audit_status
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.is_avaiable
     *
     * @return the value of t_student.is_avaiable
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getIsAvaiable() {
        return isAvaiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.is_avaiable
     *
     * @param isAvaiable the value for t_student.is_avaiable
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setIsAvaiable(Integer isAvaiable) {
        this.isAvaiable = isAvaiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.idcard_front_img
     *
     * @return the value of t_student.idcard_front_img
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getIdcardFrontImg() {
        return idcardFrontImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.idcard_front_img
     *
     * @param idcardFrontImg the value for t_student.idcard_front_img
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setIdcardFrontImg(String idcardFrontImg) {
        this.idcardFrontImg = idcardFrontImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.idcard_back_img
     *
     * @return the value of t_student.idcard_back_img
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getIdcardBackImg() {
        return idcardBackImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.idcard_back_img
     *
     * @param idcardBackImg the value for t_student.idcard_back_img
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setIdcardBackImg(String idcardBackImg) {
        this.idcardBackImg = idcardBackImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.has_paid
     *
     * @return the value of t_student.has_paid
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getHasPaid() {
        return hasPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.has_paid
     *
     * @param hasPaid the value for t_student.has_paid
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setHasPaid(Integer hasPaid) {
        this.hasPaid = hasPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.teacherid_inspector
     *
     * @return the value of t_student.teacherid_inspector
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getTeacheridInspector() {
        return teacheridInspector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.teacherid_inspector
     *
     * @param teacheridInspector the value for t_student.teacherid_inspector
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setTeacheridInspector(Integer teacheridInspector) {
        this.teacheridInspector = teacheridInspector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.teacherid_advisor
     *
     * @return the value of t_student.teacherid_advisor
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getTeacheridAdvisor() {
        return teacheridAdvisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.teacherid_advisor
     *
     * @param teacheridAdvisor the value for t_student.teacherid_advisor
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setTeacheridAdvisor(Integer teacheridAdvisor) {
        this.teacheridAdvisor = teacheridAdvisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.begin_studytime
     *
     * @return the value of t_student.begin_studytime
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Date getBeginStudytime() {
        return beginStudytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.begin_studytime
     *
     * @param beginStudytime the value for t_student.begin_studytime
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setBeginStudytime(Date beginStudytime) {
        this.beginStudytime = beginStudytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.end_studytime
     *
     * @return the value of t_student.end_studytime
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Date getEndStudytime() {
        return endStudytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.end_studytime
     *
     * @param endStudytime the value for t_student.end_studytime
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setEndStudytime(Date endStudytime) {
        this.endStudytime = endStudytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.audit_through_time
     *
     * @return the value of t_student.audit_through_time
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Date getAuditThroughTime() {
        return auditThroughTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.audit_through_time
     *
     * @param auditThroughTime the value for t_student.audit_through_time
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setAuditThroughTime(Date auditThroughTime) {
        this.auditThroughTime = auditThroughTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.school_duty
     *
     * @return the value of t_student.school_duty
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getSchoolDuty() {
        return schoolDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.school_duty
     *
     * @param schoolDuty the value for t_student.school_duty
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setSchoolDuty(String schoolDuty) {
        this.schoolDuty = schoolDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.school_subname
     *
     * @return the value of t_student.school_subname
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public String getSchoolSubname() {
        return schoolSubname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.school_subname
     *
     * @param schoolSubname the value for t_student.school_subname
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setSchoolSubname(String schoolSubname) {
        this.schoolSubname = schoolSubname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.jobservice_endtime
     *
     * @return the value of t_student.jobservice_endtime
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Date getJobserviceEndtime() {
        return jobserviceEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.jobservice_endtime
     *
     * @param jobserviceEndtime the value for t_student.jobservice_endtime
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setJobserviceEndtime(Date jobserviceEndtime) {
        this.jobserviceEndtime = jobserviceEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.jobservice_starttime
     *
     * @return the value of t_student.jobservice_starttime
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Date getJobserviceStarttime() {
        return jobserviceStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.jobservice_starttime
     *
     * @param jobserviceStarttime the value for t_student.jobservice_starttime
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setJobserviceStarttime(Date jobserviceStarttime) {
        this.jobserviceStarttime = jobserviceStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.jobstatus
     *
     * @return the value of t_student.jobstatus
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getJobstatus() {
        return jobstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.jobstatus
     *
     * @param jobstatus the value for t_student.jobstatus
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setJobstatus(Integer jobstatus) {
        this.jobstatus = jobstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.jobfromtype
     *
     * @return the value of t_student.jobfromtype
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public Integer getJobfromtype() {
        return jobfromtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.jobfromtype
     *
     * @param jobfromtype the value for t_student.jobfromtype
     *
     * @mbggenerated Tue Dec 13 16:22:14 CST 2016
     */
    public void setJobfromtype(Integer jobfromtype) {
        this.jobfromtype = jobfromtype;
    }
}