package com.lanqiao.model;

public class SysDeparment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_deparment.depid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer depid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_deparment.depname
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String depname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_deparment.parentid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_deparment.isvalid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer isvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_deparment.sortnum
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_deparment.stationids
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String stationids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_deparment.manager_userid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String managerUserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_deparment.depid
     *
     * @return the value of sys_deparment.depid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getDepid() {
        return depid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_deparment.depid
     *
     * @param depid the value for sys_deparment.depid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setDepid(Integer depid) {
        this.depid = depid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_deparment.depname
     *
     * @return the value of sys_deparment.depname
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getDepname() {
        return depname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_deparment.depname
     *
     * @param depname the value for sys_deparment.depname
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setDepname(String depname) {
        this.depname = depname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_deparment.parentid
     *
     * @return the value of sys_deparment.parentid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_deparment.parentid
     *
     * @param parentid the value for sys_deparment.parentid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_deparment.isvalid
     *
     * @return the value of sys_deparment.isvalid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_deparment.isvalid
     *
     * @param isvalid the value for sys_deparment.isvalid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_deparment.sortnum
     *
     * @return the value of sys_deparment.sortnum
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_deparment.sortnum
     *
     * @param sortnum the value for sys_deparment.sortnum
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_deparment.stationids
     *
     * @return the value of sys_deparment.stationids
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getStationids() {
        return stationids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_deparment.stationids
     *
     * @param stationids the value for sys_deparment.stationids
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setStationids(String stationids) {
        this.stationids = stationids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_deparment.manager_userid
     *
     * @return the value of sys_deparment.manager_userid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getManagerUserid() {
        return managerUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_deparment.manager_userid
     *
     * @param managerUserid the value for sys_deparment.manager_userid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setManagerUserid(String managerUserid) {
        this.managerUserid = managerUserid;
    }
}