package com.lanqiao.model;

public class SysFunction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.functionid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer functionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.functionname
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String functionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.menuids
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String menuids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.pid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.isdir
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Byte isdir;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.functionid
     *
     * @return the value of sys_function.functionid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getFunctionid() {
        return functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.functionid
     *
     * @param functionid the value for sys_function.functionid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setFunctionid(Integer functionid) {
        this.functionid = functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.functionname
     *
     * @return the value of sys_function.functionname
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getFunctionname() {
        return functionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.functionname
     *
     * @param functionname the value for sys_function.functionname
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setFunctionname(String functionname) {
        this.functionname = functionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.menuids
     *
     * @return the value of sys_function.menuids
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getMenuids() {
        return menuids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.menuids
     *
     * @param menuids the value for sys_function.menuids
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setMenuids(String menuids) {
        this.menuids = menuids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.pid
     *
     * @return the value of sys_function.pid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.pid
     *
     * @param pid the value for sys_function.pid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.isdir
     *
     * @return the value of sys_function.isdir
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Byte getIsdir() {
        return isdir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.isdir
     *
     * @param isdir the value for sys_function.isdir
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setIsdir(Byte isdir) {
        this.isdir = isdir;
    }
}