package com.lanqiao.model;

import java.util.Date;

public class SysLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.logid
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    private Integer logid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.optype
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    private String optype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.user_id
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_date
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.remote_addr
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    private String remoteAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.request_uri
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    private String requestUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.old_data
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    private String oldData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.content
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.logid
     *
     * @return the value of sys_log.logid
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.logid
     *
     * @param logid the value for sys_log.logid
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.optype
     *
     * @return the value of sys_log.optype
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public String getOptype() {
        return optype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.optype
     *
     * @param optype the value for sys_log.optype
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public void setOptype(String optype) {
        this.optype = optype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.user_id
     *
     * @return the value of sys_log.user_id
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.user_id
     *
     * @param userId the value for sys_log.user_id
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_date
     *
     * @return the value of sys_log.create_date
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_date
     *
     * @param createDate the value for sys_log.create_date
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.remote_addr
     *
     * @return the value of sys_log.remote_addr
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public String getRemoteAddr() {
        return remoteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.remote_addr
     *
     * @param remoteAddr the value for sys_log.remote_addr
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public void setRemoteAddr(String remoteAddr) {
        this.remoteAddr = remoteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.request_uri
     *
     * @return the value of sys_log.request_uri
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public String getRequestUri() {
        return requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.request_uri
     *
     * @param requestUri the value for sys_log.request_uri
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public void setRequestUri(String requestUri) {
        this.requestUri = requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.old_data
     *
     * @return the value of sys_log.old_data
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public String getOldData() {
        return oldData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.old_data
     *
     * @param oldData the value for sys_log.old_data
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public void setOldData(String oldData) {
        this.oldData = oldData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.content
     *
     * @return the value of sys_log.content
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.content
     *
     * @param content the value for sys_log.content
     *
     * @mbggenerated Mon May 08 17:22:47 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}