package com.lanqiao.model;

public class SysRoleFunction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.functionid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer functionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.roleid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.extenddata
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String extenddata;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.id
     *
     * @return the value of sys_role_function.id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.id
     *
     * @param id the value for sys_role_function.id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.functionid
     *
     * @return the value of sys_role_function.functionid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getFunctionid() {
        return functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.functionid
     *
     * @param functionid the value for sys_role_function.functionid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setFunctionid(Integer functionid) {
        this.functionid = functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.roleid
     *
     * @return the value of sys_role_function.roleid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.roleid
     *
     * @param roleid the value for sys_role_function.roleid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.extenddata
     *
     * @return the value of sys_role_function.extenddata
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getExtenddata() {
        return extenddata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.extenddata
     *
     * @param extenddata the value for sys_role_function.extenddata
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setExtenddata(String extenddata) {
        this.extenddata = extenddata;
    }
}