package com.lanqiao.model;

import java.util.Date;

public class SysSyllabus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_syllabus.syllabus_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer syllabusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_syllabus.course_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_syllabus.pid
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_syllabus.syllabus_name
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private String syllabusName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_syllabus.class_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer classTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_syllabus.create_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_syllabus.sort
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_syllabus.syllabus_id
     *
     * @return the value of sys_syllabus.syllabus_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getSyllabusId() {
        return syllabusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_syllabus.syllabus_id
     *
     * @param syllabusId the value for sys_syllabus.syllabus_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setSyllabusId(Integer syllabusId) {
        this.syllabusId = syllabusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_syllabus.course_id
     *
     * @return the value of sys_syllabus.course_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_syllabus.course_id
     *
     * @param courseId the value for sys_syllabus.course_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_syllabus.pid
     *
     * @return the value of sys_syllabus.pid
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_syllabus.pid
     *
     * @param pid the value for sys_syllabus.pid
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_syllabus.syllabus_name
     *
     * @return the value of sys_syllabus.syllabus_name
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public String getSyllabusName() {
        return syllabusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_syllabus.syllabus_name
     *
     * @param syllabusName the value for sys_syllabus.syllabus_name
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setSyllabusName(String syllabusName) {
        this.syllabusName = syllabusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_syllabus.class_time
     *
     * @return the value of sys_syllabus.class_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getClassTime() {
        return classTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_syllabus.class_time
     *
     * @param classTime the value for sys_syllabus.class_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setClassTime(Integer classTime) {
        this.classTime = classTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_syllabus.create_time
     *
     * @return the value of sys_syllabus.create_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_syllabus.create_time
     *
     * @param createTime the value for sys_syllabus.create_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_syllabus.sort
     *
     * @return the value of sys_syllabus.sort
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_syllabus.sort
     *
     * @param sort the value for sys_syllabus.sort
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}