package com.lanqiao.model;

public class SysStation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_station.stationid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer stationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_station.stationname
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String stationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_station.isvalid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer isvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_station.stationtype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer stationtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_station.sortnum
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_station.remark
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_station.stationid
     *
     * @return the value of sys_station.stationid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getStationid() {
        return stationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_station.stationid
     *
     * @param stationid the value for sys_station.stationid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setStationid(Integer stationid) {
        this.stationid = stationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_station.stationname
     *
     * @return the value of sys_station.stationname
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getStationname() {
        return stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_station.stationname
     *
     * @param stationname the value for sys_station.stationname
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setStationname(String stationname) {
        this.stationname = stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_station.isvalid
     *
     * @return the value of sys_station.isvalid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_station.isvalid
     *
     * @param isvalid the value for sys_station.isvalid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_station.stationtype
     *
     * @return the value of sys_station.stationtype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getStationtype() {
        return stationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_station.stationtype
     *
     * @param stationtype the value for sys_station.stationtype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setStationtype(Integer stationtype) {
        this.stationtype = stationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_station.sortnum
     *
     * @return the value of sys_station.sortnum
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_station.sortnum
     *
     * @param sortnum the value for sys_station.sortnum
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_station.remark
     *
     * @return the value of sys_station.remark
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_station.remark
     *
     * @param remark the value for sys_station.remark
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}