package com.lanqiao.model;

public class SysStationLevel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_station_level.levelid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer levelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_station_level.level_name
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String levelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_station_level.sortnum
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_station_level.isvalid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer isvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_station_level.remark
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_station_level.levelid
     *
     * @return the value of sys_station_level.levelid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getLevelid() {
        return levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_station_level.levelid
     *
     * @param levelid the value for sys_station_level.levelid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setLevelid(Integer levelid) {
        this.levelid = levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_station_level.level_name
     *
     * @return the value of sys_station_level.level_name
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_station_level.level_name
     *
     * @param levelName the value for sys_station_level.level_name
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_station_level.sortnum
     *
     * @return the value of sys_station_level.sortnum
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_station_level.sortnum
     *
     * @param sortnum the value for sys_station_level.sortnum
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_station_level.isvalid
     *
     * @return the value of sys_station_level.isvalid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_station_level.isvalid
     *
     * @param isvalid the value for sys_station_level.isvalid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_station_level.remark
     *
     * @return the value of sys_station_level.remark
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_station_level.remark
     *
     * @param remark the value for sys_station_level.remark
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}