package com.lanqiao.model;

import java.util.Date;

public class TClassVisitLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_visit_log.visit_id
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    private Integer visitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_visit_log.visit_time
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    private Date visitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_visit_log.creator_userid
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    private Integer creatorUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_visit_log.classid
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_visit_log.visit_content
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    private String visitContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_visit_log.visit_id
     *
     * @return the value of t_class_visit_log.visit_id
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    public Integer getVisitId() {
        return visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_visit_log.visit_id
     *
     * @param visitId the value for t_class_visit_log.visit_id
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    public void setVisitId(Integer visitId) {
        this.visitId = visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_visit_log.visit_time
     *
     * @return the value of t_class_visit_log.visit_time
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    public Date getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_visit_log.visit_time
     *
     * @param visitTime the value for t_class_visit_log.visit_time
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_visit_log.creator_userid
     *
     * @return the value of t_class_visit_log.creator_userid
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    public Integer getCreatorUserid() {
        return creatorUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_visit_log.creator_userid
     *
     * @param creatorUserid the value for t_class_visit_log.creator_userid
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    public void setCreatorUserid(Integer creatorUserid) {
        this.creatorUserid = creatorUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_visit_log.classid
     *
     * @return the value of t_class_visit_log.classid
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_visit_log.classid
     *
     * @param classid the value for t_class_visit_log.classid
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_visit_log.visit_content
     *
     * @return the value of t_class_visit_log.visit_content
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    public String getVisitContent() {
        return visitContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_visit_log.visit_content
     *
     * @param visitContent the value for t_class_visit_log.visit_content
     *
     * @mbggenerated Sat Dec 10 11:53:10 CST 2016
     */
    public void setVisitContent(String visitContent) {
        this.visitContent = visitContent;
    }
}