package com.lanqiao.model;

import java.util.Date;

public class TClassStatusLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_status_log.class_status_log_id
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    private Integer classStatusLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_status_log.class_id
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_status_log.begin_time
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_status_log.operator_userid
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    private Integer operatorUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_status_log.remark
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_status_log.newstatus
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    private Integer newstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_status_log.inputtime
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    private Date inputtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_status_log.oldstatus
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    private Integer oldstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_status_log.end_time
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_status_log.finishcount
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    private Integer finishcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_status_log.class_status_log_id
     *
     * @return the value of t_class_status_log.class_status_log_id
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public Integer getClassStatusLogId() {
        return classStatusLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_status_log.class_status_log_id
     *
     * @param classStatusLogId the value for t_class_status_log.class_status_log_id
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public void setClassStatusLogId(Integer classStatusLogId) {
        this.classStatusLogId = classStatusLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_status_log.class_id
     *
     * @return the value of t_class_status_log.class_id
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_status_log.class_id
     *
     * @param classId the value for t_class_status_log.class_id
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_status_log.begin_time
     *
     * @return the value of t_class_status_log.begin_time
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_status_log.begin_time
     *
     * @param beginTime the value for t_class_status_log.begin_time
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_status_log.operator_userid
     *
     * @return the value of t_class_status_log.operator_userid
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public Integer getOperatorUserid() {
        return operatorUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_status_log.operator_userid
     *
     * @param operatorUserid the value for t_class_status_log.operator_userid
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public void setOperatorUserid(Integer operatorUserid) {
        this.operatorUserid = operatorUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_status_log.remark
     *
     * @return the value of t_class_status_log.remark
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_status_log.remark
     *
     * @param remark the value for t_class_status_log.remark
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_status_log.newstatus
     *
     * @return the value of t_class_status_log.newstatus
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public Integer getNewstatus() {
        return newstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_status_log.newstatus
     *
     * @param newstatus the value for t_class_status_log.newstatus
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public void setNewstatus(Integer newstatus) {
        this.newstatus = newstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_status_log.inputtime
     *
     * @return the value of t_class_status_log.inputtime
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public Date getInputtime() {
        return inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_status_log.inputtime
     *
     * @param inputtime the value for t_class_status_log.inputtime
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public void setInputtime(Date inputtime) {
        this.inputtime = inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_status_log.oldstatus
     *
     * @return the value of t_class_status_log.oldstatus
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public Integer getOldstatus() {
        return oldstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_status_log.oldstatus
     *
     * @param oldstatus the value for t_class_status_log.oldstatus
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public void setOldstatus(Integer oldstatus) {
        this.oldstatus = oldstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_status_log.end_time
     *
     * @return the value of t_class_status_log.end_time
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_status_log.end_time
     *
     * @param endTime the value for t_class_status_log.end_time
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_status_log.finishcount
     *
     * @return the value of t_class_status_log.finishcount
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public Integer getFinishcount() {
        return finishcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_status_log.finishcount
     *
     * @param finishcount the value for t_class_status_log.finishcount
     *
     * @mbggenerated Fri Dec 09 20:14:07 CST 2016
     */
    public void setFinishcount(Integer finishcount) {
        this.finishcount = finishcount;
    }
}