package com.lanqiao.model;

import java.util.Date;

public class TConsole_log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_console_log.console_log_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer consoleLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_console_log.entity_name
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String entityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_console_log.entity_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_console_log.user_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_console_log.op_type
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String opType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_console_log.op_time
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_console_log.notes
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_console_log.table_name
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String tableName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_console_log.console_log_id
     *
     * @return the value of t_console_log.console_log_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getConsoleLogId() {
        return consoleLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_console_log.console_log_id
     *
     * @param consoleLogId the value for t_console_log.console_log_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setConsoleLogId(Integer consoleLogId) {
        this.consoleLogId = consoleLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_console_log.entity_name
     *
     * @return the value of t_console_log.entity_name
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_console_log.entity_name
     *
     * @param entityName the value for t_console_log.entity_name
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_console_log.entity_id
     *
     * @return the value of t_console_log.entity_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_console_log.entity_id
     *
     * @param entityId the value for t_console_log.entity_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_console_log.user_id
     *
     * @return the value of t_console_log.user_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_console_log.user_id
     *
     * @param userId the value for t_console_log.user_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_console_log.op_type
     *
     * @return the value of t_console_log.op_type
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_console_log.op_type
     *
     * @param opType the value for t_console_log.op_type
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setOpType(String opType) {
        this.opType = opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_console_log.op_time
     *
     * @return the value of t_console_log.op_time
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_console_log.op_time
     *
     * @param opTime the value for t_console_log.op_time
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_console_log.notes
     *
     * @return the value of t_console_log.notes
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_console_log.notes
     *
     * @param notes the value for t_console_log.notes
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_console_log.table_name
     *
     * @return the value of t_console_log.table_name
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_console_log.table_name
     *
     * @param tableName the value for t_console_log.table_name
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
}