package com.lanqiao.model;

public class TDataTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_tag.nnid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer nnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_tag.data_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_tag.userid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_tag.datatype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer datatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_tag.tagtype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer tagtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_tag.nnid
     *
     * @return the value of t_data_tag.nnid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getNnid() {
        return nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_tag.nnid
     *
     * @param nnid the value for t_data_tag.nnid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setNnid(Integer nnid) {
        this.nnid = nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_tag.data_id
     *
     * @return the value of t_data_tag.data_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_tag.data_id
     *
     * @param dataId the value for t_data_tag.data_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_tag.userid
     *
     * @return the value of t_data_tag.userid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_tag.userid
     *
     * @param userid the value for t_data_tag.userid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_tag.datatype
     *
     * @return the value of t_data_tag.datatype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getDatatype() {
        return datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_tag.datatype
     *
     * @param datatype the value for t_data_tag.datatype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setDatatype(Integer datatype) {
        this.datatype = datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_tag.tagtype
     *
     * @return the value of t_data_tag.tagtype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getTagtype() {
        return tagtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_tag.tagtype
     *
     * @param tagtype the value for t_data_tag.tagtype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setTagtype(Integer tagtype) {
        this.tagtype = tagtype;
    }
}