package com.lanqiao.model;

import java.util.Date;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.user_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.teach_no
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String teachNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.createtime
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.updatetime
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.school_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.teachtype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer teachtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.education
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.major
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.address
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.dep_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.level_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.station_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer stationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.user_id
     *
     * @return the value of t_teacher.user_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.user_id
     *
     * @param userId the value for t_teacher.user_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.teach_no
     *
     * @return the value of t_teacher.teach_no
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getTeachNo() {
        return teachNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.teach_no
     *
     * @param teachNo the value for t_teacher.teach_no
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setTeachNo(String teachNo) {
        this.teachNo = teachNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.createtime
     *
     * @return the value of t_teacher.createtime
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.createtime
     *
     * @param createtime the value for t_teacher.createtime
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.updatetime
     *
     * @return the value of t_teacher.updatetime
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.updatetime
     *
     * @param updatetime the value for t_teacher.updatetime
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.school_id
     *
     * @return the value of t_teacher.school_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.school_id
     *
     * @param schoolId the value for t_teacher.school_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.teachtype
     *
     * @return the value of t_teacher.teachtype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getTeachtype() {
        return teachtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.teachtype
     *
     * @param teachtype the value for t_teacher.teachtype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setTeachtype(Integer teachtype) {
        this.teachtype = teachtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.education
     *
     * @return the value of t_teacher.education
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.education
     *
     * @param education the value for t_teacher.education
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.major
     *
     * @return the value of t_teacher.major
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.major
     *
     * @param major the value for t_teacher.major
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.address
     *
     * @return the value of t_teacher.address
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.address
     *
     * @param address the value for t_teacher.address
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.dep_id
     *
     * @return the value of t_teacher.dep_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.dep_id
     *
     * @param depId the value for t_teacher.dep_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.level_id
     *
     * @return the value of t_teacher.level_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.level_id
     *
     * @param levelId the value for t_teacher.level_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.station_id
     *
     * @return the value of t_teacher.station_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.station_id
     *
     * @param stationId the value for t_teacher.station_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }
}