package com.lanqiao.model;

import java.util.Date;

public class TeacherCourseEvaluate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_evaluate.tcae_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer tcaeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_evaluate.ca_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer caId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_evaluate.we_evaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer weEvaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_evaluate.evaluate_content
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private String evaluateContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_evaluate.createe_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Date createeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_evaluate.class_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_evaluate.teacher_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_evaluate.student_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_evaluate.tcae_id
     *
     * @return the value of t_teacher_course_evaluate.tcae_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getTcaeId() {
        return tcaeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_evaluate.tcae_id
     *
     * @param tcaeId the value for t_teacher_course_evaluate.tcae_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setTcaeId(Integer tcaeId) {
        this.tcaeId = tcaeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_evaluate.ca_id
     *
     * @return the value of t_teacher_course_evaluate.ca_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getCaId() {
        return caId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_evaluate.ca_id
     *
     * @param caId the value for t_teacher_course_evaluate.ca_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setCaId(Integer caId) {
        this.caId = caId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_evaluate.we_evaluate
     *
     * @return the value of t_teacher_course_evaluate.we_evaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getWeEvaluate() {
        return weEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_evaluate.we_evaluate
     *
     * @param weEvaluate the value for t_teacher_course_evaluate.we_evaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setWeEvaluate(Integer weEvaluate) {
        this.weEvaluate = weEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_evaluate.evaluate_content
     *
     * @return the value of t_teacher_course_evaluate.evaluate_content
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public String getEvaluateContent() {
        return evaluateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_evaluate.evaluate_content
     *
     * @param evaluateContent the value for t_teacher_course_evaluate.evaluate_content
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setEvaluateContent(String evaluateContent) {
        this.evaluateContent = evaluateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_evaluate.createe_time
     *
     * @return the value of t_teacher_course_evaluate.createe_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Date getCreateeTime() {
        return createeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_evaluate.createe_time
     *
     * @param createeTime the value for t_teacher_course_evaluate.createe_time
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setCreateeTime(Date createeTime) {
        this.createeTime = createeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_evaluate.class_id
     *
     * @return the value of t_teacher_course_evaluate.class_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_evaluate.class_id
     *
     * @param classId the value for t_teacher_course_evaluate.class_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_evaluate.teacher_id
     *
     * @return the value of t_teacher_course_evaluate.teacher_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_evaluate.teacher_id
     *
     * @param teacherId the value for t_teacher_course_evaluate.teacher_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_evaluate.student_id
     *
     * @return the value of t_teacher_course_evaluate.student_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_evaluate.student_id
     *
     * @param studentId the value for t_teacher_course_evaluate.student_id
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
}