package com.lanqiao.model;

import java.util.Date;

public class TeacherCourseArrangement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_arrangement.ca_id
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    private Integer caId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_arrangement.user_id
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_arrangement.class_id
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_arrangement.ca_name
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    private String caName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_arrangement.ca_type
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    private Integer caType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_arrangement.ca_content
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    private String caContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_arrangement.start_time
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_arrangement.end_time
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_arrangement.class_time
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    private Double classTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_arrangement.create_time
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_arrangement.ca_status
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    private Integer caStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_arrangement.schooltime
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    private Date schooltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_course_arrangement.syllabus_id
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    private Integer syllabusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_arrangement.ca_id
     *
     * @return the value of t_teacher_course_arrangement.ca_id
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public Integer getCaId() {
        return caId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_arrangement.ca_id
     *
     * @param caId the value for t_teacher_course_arrangement.ca_id
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public void setCaId(Integer caId) {
        this.caId = caId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_arrangement.user_id
     *
     * @return the value of t_teacher_course_arrangement.user_id
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_arrangement.user_id
     *
     * @param userId the value for t_teacher_course_arrangement.user_id
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_arrangement.class_id
     *
     * @return the value of t_teacher_course_arrangement.class_id
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_arrangement.class_id
     *
     * @param classId the value for t_teacher_course_arrangement.class_id
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_arrangement.ca_name
     *
     * @return the value of t_teacher_course_arrangement.ca_name
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public String getCaName() {
        return caName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_arrangement.ca_name
     *
     * @param caName the value for t_teacher_course_arrangement.ca_name
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public void setCaName(String caName) {
        this.caName = caName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_arrangement.ca_type
     *
     * @return the value of t_teacher_course_arrangement.ca_type
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public Integer getCaType() {
        return caType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_arrangement.ca_type
     *
     * @param caType the value for t_teacher_course_arrangement.ca_type
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public void setCaType(Integer caType) {
        this.caType = caType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_arrangement.ca_content
     *
     * @return the value of t_teacher_course_arrangement.ca_content
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public String getCaContent() {
        return caContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_arrangement.ca_content
     *
     * @param caContent the value for t_teacher_course_arrangement.ca_content
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public void setCaContent(String caContent) {
        this.caContent = caContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_arrangement.start_time
     *
     * @return the value of t_teacher_course_arrangement.start_time
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_arrangement.start_time
     *
     * @param startTime the value for t_teacher_course_arrangement.start_time
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_arrangement.end_time
     *
     * @return the value of t_teacher_course_arrangement.end_time
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_arrangement.end_time
     *
     * @param endTime the value for t_teacher_course_arrangement.end_time
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_arrangement.class_time
     *
     * @return the value of t_teacher_course_arrangement.class_time
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public Double getClassTime() {
        return classTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_arrangement.class_time
     *
     * @param classTime the value for t_teacher_course_arrangement.class_time
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public void setClassTime(Double classTime) {
        this.classTime = classTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_arrangement.create_time
     *
     * @return the value of t_teacher_course_arrangement.create_time
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_arrangement.create_time
     *
     * @param createTime the value for t_teacher_course_arrangement.create_time
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_arrangement.ca_status
     *
     * @return the value of t_teacher_course_arrangement.ca_status
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public Integer getCaStatus() {
        return caStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_arrangement.ca_status
     *
     * @param caStatus the value for t_teacher_course_arrangement.ca_status
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public void setCaStatus(Integer caStatus) {
        this.caStatus = caStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_arrangement.schooltime
     *
     * @return the value of t_teacher_course_arrangement.schooltime
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public Date getSchooltime() {
        return schooltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_arrangement.schooltime
     *
     * @param schooltime the value for t_teacher_course_arrangement.schooltime
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public void setSchooltime(Date schooltime) {
        this.schooltime = schooltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_course_arrangement.syllabus_id
     *
     * @return the value of t_teacher_course_arrangement.syllabus_id
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public Integer getSyllabusId() {
        return syllabusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_course_arrangement.syllabus_id
     *
     * @param syllabusId the value for t_teacher_course_arrangement.syllabus_id
     *
     * @mbggenerated Tue Jul 04 11:30:33 CST 2017
     */
    public void setSyllabusId(Integer syllabusId) {
        this.syllabusId = syllabusId;
    }
}