package com.lanqiao.model;

import java.util.Date;

public class TIncomeLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_log.nnid
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    private Integer nnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_log.user_id
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_log.standard_money
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    private Long standardMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_log.favour_money
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    private Long favourMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_log.current_pay_money
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    private Long currentPayMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_log.last_pay_time
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    private Date lastPayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_log.pay_type
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_log.pay_goal
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    private Integer payGoal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_log.back_money
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    private Long backMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_log.last_back_time
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    private Date lastBackTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_log.special_audit_userid
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    private Integer specialAuditUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_log.special_audit_desc
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    private String specialAuditDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_log.nnid
     *
     * @return the value of t_income_log.nnid
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public Integer getNnid() {
        return nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_log.nnid
     *
     * @param nnid the value for t_income_log.nnid
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public void setNnid(Integer nnid) {
        this.nnid = nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_log.user_id
     *
     * @return the value of t_income_log.user_id
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_log.user_id
     *
     * @param userId the value for t_income_log.user_id
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_log.standard_money
     *
     * @return the value of t_income_log.standard_money
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public Long getStandardMoney() {
        return standardMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_log.standard_money
     *
     * @param standardMoney the value for t_income_log.standard_money
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public void setStandardMoney(Long standardMoney) {
        this.standardMoney = standardMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_log.favour_money
     *
     * @return the value of t_income_log.favour_money
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public Long getFavourMoney() {
        return favourMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_log.favour_money
     *
     * @param favourMoney the value for t_income_log.favour_money
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public void setFavourMoney(Long favourMoney) {
        this.favourMoney = favourMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_log.current_pay_money
     *
     * @return the value of t_income_log.current_pay_money
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public Long getCurrentPayMoney() {
        return currentPayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_log.current_pay_money
     *
     * @param currentPayMoney the value for t_income_log.current_pay_money
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public void setCurrentPayMoney(Long currentPayMoney) {
        this.currentPayMoney = currentPayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_log.last_pay_time
     *
     * @return the value of t_income_log.last_pay_time
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public Date getLastPayTime() {
        return lastPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_log.last_pay_time
     *
     * @param lastPayTime the value for t_income_log.last_pay_time
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public void setLastPayTime(Date lastPayTime) {
        this.lastPayTime = lastPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_log.pay_type
     *
     * @return the value of t_income_log.pay_type
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_log.pay_type
     *
     * @param payType the value for t_income_log.pay_type
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_log.pay_goal
     *
     * @return the value of t_income_log.pay_goal
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public Integer getPayGoal() {
        return payGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_log.pay_goal
     *
     * @param payGoal the value for t_income_log.pay_goal
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public void setPayGoal(Integer payGoal) {
        this.payGoal = payGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_log.back_money
     *
     * @return the value of t_income_log.back_money
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public Long getBackMoney() {
        return backMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_log.back_money
     *
     * @param backMoney the value for t_income_log.back_money
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public void setBackMoney(Long backMoney) {
        this.backMoney = backMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_log.last_back_time
     *
     * @return the value of t_income_log.last_back_time
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public Date getLastBackTime() {
        return lastBackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_log.last_back_time
     *
     * @param lastBackTime the value for t_income_log.last_back_time
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public void setLastBackTime(Date lastBackTime) {
        this.lastBackTime = lastBackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_log.special_audit_userid
     *
     * @return the value of t_income_log.special_audit_userid
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public Integer getSpecialAuditUserid() {
        return specialAuditUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_log.special_audit_userid
     *
     * @param specialAuditUserid the value for t_income_log.special_audit_userid
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public void setSpecialAuditUserid(Integer specialAuditUserid) {
        this.specialAuditUserid = specialAuditUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_log.special_audit_desc
     *
     * @return the value of t_income_log.special_audit_desc
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public String getSpecialAuditDesc() {
        return specialAuditDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_log.special_audit_desc
     *
     * @param specialAuditDesc the value for t_income_log.special_audit_desc
     *
     * @mbggenerated Thu Dec 15 17:47:02 CST 2016
     */
    public void setSpecialAuditDesc(String specialAuditDesc) {
        this.specialAuditDesc = specialAuditDesc;
    }
}