package com.lanqiao.model;

import java.util.Date;

public class TJobDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.job_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.user_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.company_name
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.company_type
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private String companyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.company_scale
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private String companyScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.position_name
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private String positionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.position_type
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Integer positionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.position_salary
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Integer positionSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.jobfrom_type
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Integer jobfromType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.entry_time
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Date entryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.teacher_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.prov_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Integer provId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.city_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.occupation_status
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Integer occupationStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.dismiss_time
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Date dismissTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.dismiss_reason
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private String dismissReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.dismiss_userid
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Integer dismissUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.entry_userid
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Integer entryUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.inputtime_in
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Date inputtimeIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_detail.inputtime_out
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    private Date inputtimeOut;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.job_id
     *
     * @return the value of t_job_detail.job_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.job_id
     *
     * @param jobId the value for t_job_detail.job_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.user_id
     *
     * @return the value of t_job_detail.user_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.user_id
     *
     * @param userId the value for t_job_detail.user_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.company_name
     *
     * @return the value of t_job_detail.company_name
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.company_name
     *
     * @param companyName the value for t_job_detail.company_name
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.company_type
     *
     * @return the value of t_job_detail.company_type
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.company_type
     *
     * @param companyType the value for t_job_detail.company_type
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.company_scale
     *
     * @return the value of t_job_detail.company_scale
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public String getCompanyScale() {
        return companyScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.company_scale
     *
     * @param companyScale the value for t_job_detail.company_scale
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setCompanyScale(String companyScale) {
        this.companyScale = companyScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.position_name
     *
     * @return the value of t_job_detail.position_name
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.position_name
     *
     * @param positionName the value for t_job_detail.position_name
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.position_type
     *
     * @return the value of t_job_detail.position_type
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Integer getPositionType() {
        return positionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.position_type
     *
     * @param positionType the value for t_job_detail.position_type
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setPositionType(Integer positionType) {
        this.positionType = positionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.position_salary
     *
     * @return the value of t_job_detail.position_salary
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Integer getPositionSalary() {
        return positionSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.position_salary
     *
     * @param positionSalary the value for t_job_detail.position_salary
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setPositionSalary(Integer positionSalary) {
        this.positionSalary = positionSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.jobfrom_type
     *
     * @return the value of t_job_detail.jobfrom_type
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Integer getJobfromType() {
        return jobfromType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.jobfrom_type
     *
     * @param jobfromType the value for t_job_detail.jobfrom_type
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setJobfromType(Integer jobfromType) {
        this.jobfromType = jobfromType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.entry_time
     *
     * @return the value of t_job_detail.entry_time
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.entry_time
     *
     * @param entryTime the value for t_job_detail.entry_time
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.teacher_id
     *
     * @return the value of t_job_detail.teacher_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.teacher_id
     *
     * @param teacherId the value for t_job_detail.teacher_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.prov_id
     *
     * @return the value of t_job_detail.prov_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Integer getProvId() {
        return provId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.prov_id
     *
     * @param provId the value for t_job_detail.prov_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setProvId(Integer provId) {
        this.provId = provId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.city_id
     *
     * @return the value of t_job_detail.city_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.city_id
     *
     * @param cityId the value for t_job_detail.city_id
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.occupation_status
     *
     * @return the value of t_job_detail.occupation_status
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Integer getOccupationStatus() {
        return occupationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.occupation_status
     *
     * @param occupationStatus the value for t_job_detail.occupation_status
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setOccupationStatus(Integer occupationStatus) {
        this.occupationStatus = occupationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.dismiss_time
     *
     * @return the value of t_job_detail.dismiss_time
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Date getDismissTime() {
        return dismissTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.dismiss_time
     *
     * @param dismissTime the value for t_job_detail.dismiss_time
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setDismissTime(Date dismissTime) {
        this.dismissTime = dismissTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.dismiss_reason
     *
     * @return the value of t_job_detail.dismiss_reason
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public String getDismissReason() {
        return dismissReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.dismiss_reason
     *
     * @param dismissReason the value for t_job_detail.dismiss_reason
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setDismissReason(String dismissReason) {
        this.dismissReason = dismissReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.dismiss_userid
     *
     * @return the value of t_job_detail.dismiss_userid
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Integer getDismissUserid() {
        return dismissUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.dismiss_userid
     *
     * @param dismissUserid the value for t_job_detail.dismiss_userid
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setDismissUserid(Integer dismissUserid) {
        this.dismissUserid = dismissUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.entry_userid
     *
     * @return the value of t_job_detail.entry_userid
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Integer getEntryUserid() {
        return entryUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.entry_userid
     *
     * @param entryUserid the value for t_job_detail.entry_userid
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setEntryUserid(Integer entryUserid) {
        this.entryUserid = entryUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.inputtime_in
     *
     * @return the value of t_job_detail.inputtime_in
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Date getInputtimeIn() {
        return inputtimeIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.inputtime_in
     *
     * @param inputtimeIn the value for t_job_detail.inputtime_in
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setInputtimeIn(Date inputtimeIn) {
        this.inputtimeIn = inputtimeIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_detail.inputtime_out
     *
     * @return the value of t_job_detail.inputtime_out
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public Date getInputtimeOut() {
        return inputtimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_detail.inputtime_out
     *
     * @param inputtimeOut the value for t_job_detail.inputtime_out
     *
     * @mbggenerated Tue Dec 27 14:38:22 CST 2016
     */
    public void setInputtimeOut(Date inputtimeOut) {
        this.inputtimeOut = inputtimeOut;
    }
}