package com.lanqiao.model;

import java.util.Date;

public class TLqclass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.lq_class_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Integer lqClassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.class_name
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.start_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.expect_starttime
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Date expectStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.monitor_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Integer monitorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.chr_teacher_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Integer chrTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.status
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.course_type
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Integer courseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.com_teacher_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Integer comTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.cep_teacher_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Integer cepTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.type_pre
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private String typePre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.graduate_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Date graduateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.expect_graduate_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Date expectGraduateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.qq_group
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private String qqGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.real_count
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Integer realCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.stu_count
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Integer stuCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.type_real
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private String typeReal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.inv_teacher_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Integer invTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.create_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.update_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.create_user_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.close_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Date closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.class_goal
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private String classGoal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.expect_school_endtime
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Date expectSchoolEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lqclass.school_endtime
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    private Date schoolEndtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.lq_class_id
     *
     * @return the value of t_lqclass.lq_class_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Integer getLqClassId() {
        return lqClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.lq_class_id
     *
     * @param lqClassId the value for t_lqclass.lq_class_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setLqClassId(Integer lqClassId) {
        this.lqClassId = lqClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.class_name
     *
     * @return the value of t_lqclass.class_name
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.class_name
     *
     * @param className the value for t_lqclass.class_name
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.start_time
     *
     * @return the value of t_lqclass.start_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.start_time
     *
     * @param startTime the value for t_lqclass.start_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.expect_starttime
     *
     * @return the value of t_lqclass.expect_starttime
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Date getExpectStarttime() {
        return expectStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.expect_starttime
     *
     * @param expectStarttime the value for t_lqclass.expect_starttime
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setExpectStarttime(Date expectStarttime) {
        this.expectStarttime = expectStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.monitor_id
     *
     * @return the value of t_lqclass.monitor_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Integer getMonitorId() {
        return monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.monitor_id
     *
     * @param monitorId the value for t_lqclass.monitor_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setMonitorId(Integer monitorId) {
        this.monitorId = monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.chr_teacher_id
     *
     * @return the value of t_lqclass.chr_teacher_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Integer getChrTeacherId() {
        return chrTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.chr_teacher_id
     *
     * @param chrTeacherId the value for t_lqclass.chr_teacher_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setChrTeacherId(Integer chrTeacherId) {
        this.chrTeacherId = chrTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.status
     *
     * @return the value of t_lqclass.status
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.status
     *
     * @param status the value for t_lqclass.status
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.course_type
     *
     * @return the value of t_lqclass.course_type
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Integer getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.course_type
     *
     * @param courseType the value for t_lqclass.course_type
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setCourseType(Integer courseType) {
        this.courseType = courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.com_teacher_id
     *
     * @return the value of t_lqclass.com_teacher_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Integer getComTeacherId() {
        return comTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.com_teacher_id
     *
     * @param comTeacherId the value for t_lqclass.com_teacher_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setComTeacherId(Integer comTeacherId) {
        this.comTeacherId = comTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.cep_teacher_id
     *
     * @return the value of t_lqclass.cep_teacher_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Integer getCepTeacherId() {
        return cepTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.cep_teacher_id
     *
     * @param cepTeacherId the value for t_lqclass.cep_teacher_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setCepTeacherId(Integer cepTeacherId) {
        this.cepTeacherId = cepTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.type_pre
     *
     * @return the value of t_lqclass.type_pre
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public String getTypePre() {
        return typePre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.type_pre
     *
     * @param typePre the value for t_lqclass.type_pre
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setTypePre(String typePre) {
        this.typePre = typePre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.graduate_time
     *
     * @return the value of t_lqclass.graduate_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Date getGraduateTime() {
        return graduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.graduate_time
     *
     * @param graduateTime the value for t_lqclass.graduate_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setGraduateTime(Date graduateTime) {
        this.graduateTime = graduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.expect_graduate_time
     *
     * @return the value of t_lqclass.expect_graduate_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Date getExpectGraduateTime() {
        return expectGraduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.expect_graduate_time
     *
     * @param expectGraduateTime the value for t_lqclass.expect_graduate_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setExpectGraduateTime(Date expectGraduateTime) {
        this.expectGraduateTime = expectGraduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.qq_group
     *
     * @return the value of t_lqclass.qq_group
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public String getQqGroup() {
        return qqGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.qq_group
     *
     * @param qqGroup the value for t_lqclass.qq_group
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setQqGroup(String qqGroup) {
        this.qqGroup = qqGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.real_count
     *
     * @return the value of t_lqclass.real_count
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Integer getRealCount() {
        return realCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.real_count
     *
     * @param realCount the value for t_lqclass.real_count
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setRealCount(Integer realCount) {
        this.realCount = realCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.stu_count
     *
     * @return the value of t_lqclass.stu_count
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Integer getStuCount() {
        return stuCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.stu_count
     *
     * @param stuCount the value for t_lqclass.stu_count
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setStuCount(Integer stuCount) {
        this.stuCount = stuCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.type_real
     *
     * @return the value of t_lqclass.type_real
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public String getTypeReal() {
        return typeReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.type_real
     *
     * @param typeReal the value for t_lqclass.type_real
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setTypeReal(String typeReal) {
        this.typeReal = typeReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.inv_teacher_id
     *
     * @return the value of t_lqclass.inv_teacher_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Integer getInvTeacherId() {
        return invTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.inv_teacher_id
     *
     * @param invTeacherId the value for t_lqclass.inv_teacher_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setInvTeacherId(Integer invTeacherId) {
        this.invTeacherId = invTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.create_time
     *
     * @return the value of t_lqclass.create_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.create_time
     *
     * @param createTime the value for t_lqclass.create_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.update_time
     *
     * @return the value of t_lqclass.update_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.update_time
     *
     * @param updateTime the value for t_lqclass.update_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.create_user_id
     *
     * @return the value of t_lqclass.create_user_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.create_user_id
     *
     * @param createUserId the value for t_lqclass.create_user_id
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.close_time
     *
     * @return the value of t_lqclass.close_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.close_time
     *
     * @param closeTime the value for t_lqclass.close_time
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.class_goal
     *
     * @return the value of t_lqclass.class_goal
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public String getClassGoal() {
        return classGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.class_goal
     *
     * @param classGoal the value for t_lqclass.class_goal
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setClassGoal(String classGoal) {
        this.classGoal = classGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.expect_school_endtime
     *
     * @return the value of t_lqclass.expect_school_endtime
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Date getExpectSchoolEndtime() {
        return expectSchoolEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.expect_school_endtime
     *
     * @param expectSchoolEndtime the value for t_lqclass.expect_school_endtime
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setExpectSchoolEndtime(Date expectSchoolEndtime) {
        this.expectSchoolEndtime = expectSchoolEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lqclass.school_endtime
     *
     * @return the value of t_lqclass.school_endtime
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public Date getSchoolEndtime() {
        return schoolEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lqclass.school_endtime
     *
     * @param schoolEndtime the value for t_lqclass.school_endtime
     *
     * @mbggenerated Mon Dec 12 18:23:22 CST 2016
     */
    public void setSchoolEndtime(Date schoolEndtime) {
        this.schoolEndtime = schoolEndtime;
    }
}