package com.lanqiao.model;

import java.util.Date;

public class TSmssendLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smssend_log.nnid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer nnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smssend_log.destphone
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String destphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smssend_log.sendtime
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smssend_log.smscode
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String smscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smssend_log.platform
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer platform;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smssend_log.nnid
     *
     * @return the value of t_smssend_log.nnid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getNnid() {
        return nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smssend_log.nnid
     *
     * @param nnid the value for t_smssend_log.nnid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setNnid(Integer nnid) {
        this.nnid = nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smssend_log.destphone
     *
     * @return the value of t_smssend_log.destphone
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getDestphone() {
        return destphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smssend_log.destphone
     *
     * @param destphone the value for t_smssend_log.destphone
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setDestphone(String destphone) {
        this.destphone = destphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smssend_log.sendtime
     *
     * @return the value of t_smssend_log.sendtime
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smssend_log.sendtime
     *
     * @param sendtime the value for t_smssend_log.sendtime
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smssend_log.smscode
     *
     * @return the value of t_smssend_log.smscode
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getSmscode() {
        return smscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smssend_log.smscode
     *
     * @param smscode the value for t_smssend_log.smscode
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setSmscode(String smscode) {
        this.smscode = smscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smssend_log.platform
     *
     * @return the value of t_smssend_log.platform
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smssend_log.platform
     *
     * @param platform the value for t_smssend_log.platform
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }
}