package com.lanqiao.model;

import java.util.Date;

public class TStudentRefundLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_refund_log.student_refund_log_id
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer studentRefundLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_refund_log.cost_type
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer costType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_refund_log.refund_money
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Long refundMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_refund_log.create_date
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_refund_log.approval_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer approvalUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_refund_log.agency_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer agencyUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_refund_log.remarks
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_refund_log.refund_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer refundUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_refund_log.oper_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer operUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_refund_log.inputtime
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Date inputtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_refund_log.student_refund_log_id
     *
     * @return the value of t_student_refund_log.student_refund_log_id
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getStudentRefundLogId() {
        return studentRefundLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_refund_log.student_refund_log_id
     *
     * @param studentRefundLogId the value for t_student_refund_log.student_refund_log_id
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setStudentRefundLogId(Integer studentRefundLogId) {
        this.studentRefundLogId = studentRefundLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_refund_log.cost_type
     *
     * @return the value of t_student_refund_log.cost_type
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getCostType() {
        return costType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_refund_log.cost_type
     *
     * @param costType the value for t_student_refund_log.cost_type
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setCostType(Integer costType) {
        this.costType = costType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_refund_log.refund_money
     *
     * @return the value of t_student_refund_log.refund_money
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Long getRefundMoney() {
        return refundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_refund_log.refund_money
     *
     * @param refundMoney the value for t_student_refund_log.refund_money
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setRefundMoney(Long refundMoney) {
        this.refundMoney = refundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_refund_log.create_date
     *
     * @return the value of t_student_refund_log.create_date
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_refund_log.create_date
     *
     * @param createDate the value for t_student_refund_log.create_date
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_refund_log.approval_userid
     *
     * @return the value of t_student_refund_log.approval_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getApprovalUserid() {
        return approvalUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_refund_log.approval_userid
     *
     * @param approvalUserid the value for t_student_refund_log.approval_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setApprovalUserid(Integer approvalUserid) {
        this.approvalUserid = approvalUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_refund_log.agency_userid
     *
     * @return the value of t_student_refund_log.agency_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getAgencyUserid() {
        return agencyUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_refund_log.agency_userid
     *
     * @param agencyUserid the value for t_student_refund_log.agency_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setAgencyUserid(Integer agencyUserid) {
        this.agencyUserid = agencyUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_refund_log.remarks
     *
     * @return the value of t_student_refund_log.remarks
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_refund_log.remarks
     *
     * @param remarks the value for t_student_refund_log.remarks
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_refund_log.refund_userid
     *
     * @return the value of t_student_refund_log.refund_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getRefundUserid() {
        return refundUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_refund_log.refund_userid
     *
     * @param refundUserid the value for t_student_refund_log.refund_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setRefundUserid(Integer refundUserid) {
        this.refundUserid = refundUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_refund_log.oper_userid
     *
     * @return the value of t_student_refund_log.oper_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getOperUserid() {
        return operUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_refund_log.oper_userid
     *
     * @param operUserid the value for t_student_refund_log.oper_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setOperUserid(Integer operUserid) {
        this.operUserid = operUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_refund_log.inputtime
     *
     * @return the value of t_student_refund_log.inputtime
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Date getInputtime() {
        return inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_refund_log.inputtime
     *
     * @param inputtime the value for t_student_refund_log.inputtime
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setInputtime(Date inputtime) {
        this.inputtime = inputtime;
    }
}