package com.lanqiao.model;

import java.util.Date;

public class TStudentReceivableLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_receivable_log.student_receivable_log_id
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer studentReceivableLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_receivable_log.receivable_money
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Long receivableMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_receivable_log.create_date
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_receivable_log.pay_way
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer payWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_receivable_log.agency_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer agencyUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_receivable_log.remarks
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_receivable_log.receivable_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer receivableUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_receivable_log.cost_type
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer costType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_receivable_log.oper_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer operUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_receivable_log.inputtime
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Date inputtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_receivable_log.student_receivable_log_id
     *
     * @return the value of t_student_receivable_log.student_receivable_log_id
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getStudentReceivableLogId() {
        return studentReceivableLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_receivable_log.student_receivable_log_id
     *
     * @param studentReceivableLogId the value for t_student_receivable_log.student_receivable_log_id
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setStudentReceivableLogId(Integer studentReceivableLogId) {
        this.studentReceivableLogId = studentReceivableLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_receivable_log.receivable_money
     *
     * @return the value of t_student_receivable_log.receivable_money
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Long getReceivableMoney() {
        return receivableMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_receivable_log.receivable_money
     *
     * @param receivableMoney the value for t_student_receivable_log.receivable_money
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setReceivableMoney(Long receivableMoney) {
        this.receivableMoney = receivableMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_receivable_log.create_date
     *
     * @return the value of t_student_receivable_log.create_date
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_receivable_log.create_date
     *
     * @param createDate the value for t_student_receivable_log.create_date
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_receivable_log.pay_way
     *
     * @return the value of t_student_receivable_log.pay_way
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_receivable_log.pay_way
     *
     * @param payWay the value for t_student_receivable_log.pay_way
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setPayWay(Integer payWay) {
        this.payWay = payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_receivable_log.agency_userid
     *
     * @return the value of t_student_receivable_log.agency_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getAgencyUserid() {
        return agencyUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_receivable_log.agency_userid
     *
     * @param agencyUserid the value for t_student_receivable_log.agency_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setAgencyUserid(Integer agencyUserid) {
        this.agencyUserid = agencyUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_receivable_log.remarks
     *
     * @return the value of t_student_receivable_log.remarks
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_receivable_log.remarks
     *
     * @param remarks the value for t_student_receivable_log.remarks
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_receivable_log.receivable_userid
     *
     * @return the value of t_student_receivable_log.receivable_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getReceivableUserid() {
        return receivableUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_receivable_log.receivable_userid
     *
     * @param receivableUserid the value for t_student_receivable_log.receivable_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setReceivableUserid(Integer receivableUserid) {
        this.receivableUserid = receivableUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_receivable_log.cost_type
     *
     * @return the value of t_student_receivable_log.cost_type
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getCostType() {
        return costType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_receivable_log.cost_type
     *
     * @param costType the value for t_student_receivable_log.cost_type
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setCostType(Integer costType) {
        this.costType = costType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_receivable_log.oper_userid
     *
     * @return the value of t_student_receivable_log.oper_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getOperUserid() {
        return operUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_receivable_log.oper_userid
     *
     * @param operUserid the value for t_student_receivable_log.oper_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setOperUserid(Integer operUserid) {
        this.operUserid = operUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_receivable_log.inputtime
     *
     * @return the value of t_student_receivable_log.inputtime
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Date getInputtime() {
        return inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_receivable_log.inputtime
     *
     * @param inputtime the value for t_student_receivable_log.inputtime
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setInputtime(Date inputtime) {
        this.inputtime = inputtime;
    }
}