package com.lanqiao.model;

import java.util.Date;

public class TStudentRemissionLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_remission_log.student_remission_log_id
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer studentRemissionLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_remission_log.cost_type
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer costType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_remission_log.reduce_money
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Long reduceMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_remission_log.create_date
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_remission_log.approral_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer approralUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_remission_log.remarks
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_remission_log.remission_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer remissionUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_remission_log.oper_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Integer operUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_remission_log.inputtime
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    private Date inputtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_remission_log.student_remission_log_id
     *
     * @return the value of t_student_remission_log.student_remission_log_id
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getStudentRemissionLogId() {
        return studentRemissionLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_remission_log.student_remission_log_id
     *
     * @param studentRemissionLogId the value for t_student_remission_log.student_remission_log_id
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setStudentRemissionLogId(Integer studentRemissionLogId) {
        this.studentRemissionLogId = studentRemissionLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_remission_log.cost_type
     *
     * @return the value of t_student_remission_log.cost_type
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getCostType() {
        return costType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_remission_log.cost_type
     *
     * @param costType the value for t_student_remission_log.cost_type
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setCostType(Integer costType) {
        this.costType = costType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_remission_log.reduce_money
     *
     * @return the value of t_student_remission_log.reduce_money
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Long getReduceMoney() {
        return reduceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_remission_log.reduce_money
     *
     * @param reduceMoney the value for t_student_remission_log.reduce_money
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setReduceMoney(Long reduceMoney) {
        this.reduceMoney = reduceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_remission_log.create_date
     *
     * @return the value of t_student_remission_log.create_date
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_remission_log.create_date
     *
     * @param createDate the value for t_student_remission_log.create_date
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_remission_log.approral_userid
     *
     * @return the value of t_student_remission_log.approral_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getApproralUserid() {
        return approralUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_remission_log.approral_userid
     *
     * @param approralUserid the value for t_student_remission_log.approral_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setApproralUserid(Integer approralUserid) {
        this.approralUserid = approralUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_remission_log.remarks
     *
     * @return the value of t_student_remission_log.remarks
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_remission_log.remarks
     *
     * @param remarks the value for t_student_remission_log.remarks
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_remission_log.remission_userid
     *
     * @return the value of t_student_remission_log.remission_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getRemissionUserid() {
        return remissionUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_remission_log.remission_userid
     *
     * @param remissionUserid the value for t_student_remission_log.remission_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setRemissionUserid(Integer remissionUserid) {
        this.remissionUserid = remissionUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_remission_log.oper_userid
     *
     * @return the value of t_student_remission_log.oper_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Integer getOperUserid() {
        return operUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_remission_log.oper_userid
     *
     * @param operUserid the value for t_student_remission_log.oper_userid
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setOperUserid(Integer operUserid) {
        this.operUserid = operUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_remission_log.inputtime
     *
     * @return the value of t_student_remission_log.inputtime
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public Date getInputtime() {
        return inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_remission_log.inputtime
     *
     * @param inputtime the value for t_student_remission_log.inputtime
     *
     * @mbggenerated Wed Dec 28 15:47:19 CST 2016
     */
    public void setInputtime(Date inputtime) {
        this.inputtime = inputtime;
    }
}