package com.lanqiao.model;

public class TStuno {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stuno.stuno_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer stunoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stuno.course_type
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer courseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stuno.course_total
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer courseTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stuno.years
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String years;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stuno.stuno_id
     *
     * @return the value of t_stuno.stuno_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getStunoId() {
        return stunoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stuno.stuno_id
     *
     * @param stunoId the value for t_stuno.stuno_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setStunoId(Integer stunoId) {
        this.stunoId = stunoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stuno.course_type
     *
     * @return the value of t_stuno.course_type
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stuno.course_type
     *
     * @param courseType the value for t_stuno.course_type
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setCourseType(Integer courseType) {
        this.courseType = courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stuno.course_total
     *
     * @return the value of t_stuno.course_total
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getCourseTotal() {
        return courseTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stuno.course_total
     *
     * @param courseTotal the value for t_stuno.course_total
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setCourseTotal(Integer courseTotal) {
        this.courseTotal = courseTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stuno.years
     *
     * @return the value of t_stuno.years
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stuno.years
     *
     * @param years the value for t_stuno.years
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setYears(String years) {
        this.years = years;
    }
}