package com.lanqiao.model;

import java.util.Date;

public class TStudentStatusLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_status_log.student_status_log_id
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    private Integer studentStatusLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_status_log.user_id
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_status_log.begin_time
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_status_log.endt_time
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    private Date endtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_status_log.operator_userid
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    private Integer operatorUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_status_log.remark
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_status_log.newstatus
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    private Integer newstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_status_log.inputtime
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    private Date inputtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_status_log.oldstatus
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    private Integer oldstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_status_log.finish_count
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    private Integer finishCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_status_log.backtime
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    private Date backtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_status_log.lqclassid
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    private Integer lqclassid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_status_log.student_status_log_id
     *
     * @return the value of t_student_status_log.student_status_log_id
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public Integer getStudentStatusLogId() {
        return studentStatusLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_status_log.student_status_log_id
     *
     * @param studentStatusLogId the value for t_student_status_log.student_status_log_id
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public void setStudentStatusLogId(Integer studentStatusLogId) {
        this.studentStatusLogId = studentStatusLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_status_log.user_id
     *
     * @return the value of t_student_status_log.user_id
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_status_log.user_id
     *
     * @param userId the value for t_student_status_log.user_id
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_status_log.begin_time
     *
     * @return the value of t_student_status_log.begin_time
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_status_log.begin_time
     *
     * @param beginTime the value for t_student_status_log.begin_time
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_status_log.endt_time
     *
     * @return the value of t_student_status_log.endt_time
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public Date getEndtTime() {
        return endtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_status_log.endt_time
     *
     * @param endtTime the value for t_student_status_log.endt_time
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public void setEndtTime(Date endtTime) {
        this.endtTime = endtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_status_log.operator_userid
     *
     * @return the value of t_student_status_log.operator_userid
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public Integer getOperatorUserid() {
        return operatorUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_status_log.operator_userid
     *
     * @param operatorUserid the value for t_student_status_log.operator_userid
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public void setOperatorUserid(Integer operatorUserid) {
        this.operatorUserid = operatorUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_status_log.remark
     *
     * @return the value of t_student_status_log.remark
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_status_log.remark
     *
     * @param remark the value for t_student_status_log.remark
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_status_log.newstatus
     *
     * @return the value of t_student_status_log.newstatus
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public Integer getNewstatus() {
        return newstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_status_log.newstatus
     *
     * @param newstatus the value for t_student_status_log.newstatus
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public void setNewstatus(Integer newstatus) {
        this.newstatus = newstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_status_log.inputtime
     *
     * @return the value of t_student_status_log.inputtime
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public Date getInputtime() {
        return inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_status_log.inputtime
     *
     * @param inputtime the value for t_student_status_log.inputtime
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public void setInputtime(Date inputtime) {
        this.inputtime = inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_status_log.oldstatus
     *
     * @return the value of t_student_status_log.oldstatus
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public Integer getOldstatus() {
        return oldstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_status_log.oldstatus
     *
     * @param oldstatus the value for t_student_status_log.oldstatus
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public void setOldstatus(Integer oldstatus) {
        this.oldstatus = oldstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_status_log.finish_count
     *
     * @return the value of t_student_status_log.finish_count
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public Integer getFinishCount() {
        return finishCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_status_log.finish_count
     *
     * @param finishCount the value for t_student_status_log.finish_count
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public void setFinishCount(Integer finishCount) {
        this.finishCount = finishCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_status_log.backtime
     *
     * @return the value of t_student_status_log.backtime
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public Date getBacktime() {
        return backtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_status_log.backtime
     *
     * @param backtime the value for t_student_status_log.backtime
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public void setBacktime(Date backtime) {
        this.backtime = backtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_status_log.lqclassid
     *
     * @return the value of t_student_status_log.lqclassid
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public Integer getLqclassid() {
        return lqclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_status_log.lqclassid
     *
     * @param lqclassid the value for t_student_status_log.lqclassid
     *
     * @mbggenerated Fri Dec 23 11:24:20 CST 2016
     */
    public void setLqclassid(Integer lqclassid) {
        this.lqclassid = lqclassid;
    }
}