package com.lanqiao.model;

import java.util.Date;

public class TStudentclassLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studentclass_log.studentclass_log_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer studentclassLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studentclass_log.class_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studentclass_log.user_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studentclass_log.create_time
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studentclass_log.exit_time
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Date exitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studentclass_log.remark
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studentclass_log.oper_userid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer operUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studentclass_log.finishcount
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer finishcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studentclass_log.studentclass_log_id
     *
     * @return the value of t_studentclass_log.studentclass_log_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getStudentclassLogId() {
        return studentclassLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studentclass_log.studentclass_log_id
     *
     * @param studentclassLogId the value for t_studentclass_log.studentclass_log_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setStudentclassLogId(Integer studentclassLogId) {
        this.studentclassLogId = studentclassLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studentclass_log.class_id
     *
     * @return the value of t_studentclass_log.class_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studentclass_log.class_id
     *
     * @param classId the value for t_studentclass_log.class_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studentclass_log.user_id
     *
     * @return the value of t_studentclass_log.user_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studentclass_log.user_id
     *
     * @param userId the value for t_studentclass_log.user_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studentclass_log.create_time
     *
     * @return the value of t_studentclass_log.create_time
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studentclass_log.create_time
     *
     * @param createTime the value for t_studentclass_log.create_time
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studentclass_log.exit_time
     *
     * @return the value of t_studentclass_log.exit_time
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Date getExitTime() {
        return exitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studentclass_log.exit_time
     *
     * @param exitTime the value for t_studentclass_log.exit_time
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setExitTime(Date exitTime) {
        this.exitTime = exitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studentclass_log.remark
     *
     * @return the value of t_studentclass_log.remark
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studentclass_log.remark
     *
     * @param remark the value for t_studentclass_log.remark
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studentclass_log.oper_userid
     *
     * @return the value of t_studentclass_log.oper_userid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getOperUserid() {
        return operUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studentclass_log.oper_userid
     *
     * @param operUserid the value for t_studentclass_log.oper_userid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setOperUserid(Integer operUserid) {
        this.operUserid = operUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studentclass_log.finishcount
     *
     * @return the value of t_studentclass_log.finishcount
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getFinishcount() {
        return finishcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studentclass_log.finishcount
     *
     * @param finishcount the value for t_studentclass_log.finishcount
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setFinishcount(Integer finishcount) {
        this.finishcount = finishcount;
    }
}