package com.lanqiao.model;

import java.util.Date;

public class TUserBind {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_bind.nnid
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private Integer nnid;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_bind.openid
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String openid;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_bind.openid_type
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private Integer openidType;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_bind.createtime
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private Date createtime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user_bind.user_id
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private Integer userId;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user_bind.nnid
	 *
	 * @return the value of t_user_bind.nnid
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public Integer getNnid() {
		return nnid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user_bind.nnid
	 *
	 * @param nnid the value for t_user_bind.nnid
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setNnid(Integer nnid) {
		this.nnid = nnid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user_bind.openid
	 *
	 * @return the value of t_user_bind.openid
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user_bind.openid
	 *
	 * @param openid the value for t_user_bind.openid
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user_bind.openid_type
	 *
	 * @return the value of t_user_bind.openid_type
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public Integer getOpenidType() {
		return openidType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user_bind.openid_type
	 *
	 * @param openidType the value for t_user_bind.openid_type
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setOpenidType(Integer openidType) {
		this.openidType = openidType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user_bind.createtime
	 *
	 * @return the value of t_user_bind.createtime
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user_bind.createtime
	 *
	 * @param createtime the value for t_user_bind.createtime
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user_bind.user_id
	 *
	 * @return the value of t_user_bind.user_id
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user_bind.user_id
	 *
	 * @param userId the value for t_user_bind.user_id
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Override
	public String toString() {
		return "TUserBind [nnid=" + nnid + ", openid=" + openid + ", openidType=" + openidType + ", createtime="
				+ createtime + ", userId=" + userId + "]";
	}

}