package com.lanqiao.model;

public class TUserDataAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_data_auth.user_data_anth_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer userDataAnthId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_data_auth.user_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_data_auth.data_type
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_data_auth.data_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String dataId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_data_auth.user_data_anth_id
     *
     * @return the value of t_user_data_auth.user_data_anth_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getUserDataAnthId() {
        return userDataAnthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_data_auth.user_data_anth_id
     *
     * @param userDataAnthId the value for t_user_data_auth.user_data_anth_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setUserDataAnthId(Integer userDataAnthId) {
        this.userDataAnthId = userDataAnthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_data_auth.user_id
     *
     * @return the value of t_user_data_auth.user_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_data_auth.user_id
     *
     * @param userId the value for t_user_data_auth.user_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_data_auth.data_type
     *
     * @return the value of t_user_data_auth.data_type
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_data_auth.data_type
     *
     * @param dataType the value for t_user_data_auth.data_type
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_data_auth.data_id
     *
     * @return the value of t_user_data_auth.data_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_data_auth.data_id
     *
     * @param dataId the value for t_user_data_auth.data_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }
}