package com.lanqiao.model;

public class TVisitSubLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_sub_log.nnid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer nnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_sub_log.visit_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer visitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_sub_log.data_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer dataId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_sub_log.nnid
     *
     * @return the value of t_visit_sub_log.nnid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getNnid() {
        return nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_sub_log.nnid
     *
     * @param nnid the value for t_visit_sub_log.nnid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setNnid(Integer nnid) {
        this.nnid = nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_sub_log.visit_id
     *
     * @return the value of t_visit_sub_log.visit_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getVisitId() {
        return visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_sub_log.visit_id
     *
     * @param visitId the value for t_visit_sub_log.visit_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setVisitId(Integer visitId) {
        this.visitId = visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_sub_log.data_id
     *
     * @return the value of t_visit_sub_log.data_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_sub_log.data_id
     *
     * @param dataId the value for t_visit_sub_log.data_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }
}