package com.lanqiao.model;

import java.util.Date;

public class TVisit_log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_log.visit_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer visitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_log.visit_time
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Date visitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_log.visit_goal
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String visitGoal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_log.visit_datatype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer visitDatatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_log.creator_userid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Integer creatorUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_log.createtime
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_log.visit_content
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    private String visitContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_log.visit_id
     *
     * @return the value of t_visit_log.visit_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getVisitId() {
        return visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_log.visit_id
     *
     * @param visitId the value for t_visit_log.visit_id
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setVisitId(Integer visitId) {
        this.visitId = visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_log.visit_time
     *
     * @return the value of t_visit_log.visit_time
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Date getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_log.visit_time
     *
     * @param visitTime the value for t_visit_log.visit_time
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_log.visit_goal
     *
     * @return the value of t_visit_log.visit_goal
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getVisitGoal() {
        return visitGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_log.visit_goal
     *
     * @param visitGoal the value for t_visit_log.visit_goal
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setVisitGoal(String visitGoal) {
        this.visitGoal = visitGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_log.visit_datatype
     *
     * @return the value of t_visit_log.visit_datatype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getVisitDatatype() {
        return visitDatatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_log.visit_datatype
     *
     * @param visitDatatype the value for t_visit_log.visit_datatype
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setVisitDatatype(Integer visitDatatype) {
        this.visitDatatype = visitDatatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_log.creator_userid
     *
     * @return the value of t_visit_log.creator_userid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Integer getCreatorUserid() {
        return creatorUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_log.creator_userid
     *
     * @param creatorUserid the value for t_visit_log.creator_userid
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setCreatorUserid(Integer creatorUserid) {
        this.creatorUserid = creatorUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_log.createtime
     *
     * @return the value of t_visit_log.createtime
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_log.createtime
     *
     * @param createtime the value for t_visit_log.createtime
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_log.visit_content
     *
     * @return the value of t_visit_log.visit_content
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public String getVisitContent() {
        return visitContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_log.visit_content
     *
     * @param visitContent the value for t_visit_log.visit_content
     *
     * @mbggenerated Fri Dec 09 17:16:58 CST 2016
     */
    public void setVisitContent(String visitContent) {
        this.visitContent = visitContent;
    }
}