package com.lanqiao.model;

import java.util.Date;

public class User {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.user_id
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private Integer userId;
	private Integer ssoUserid;
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.login_tel
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String loginTel;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.login_email
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String loginEmail;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.login_lq
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String loginLq;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.password
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.salt
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String salt;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.real_name
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String realName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.sex
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String sex;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.qq
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String qq;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.email
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.tel
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String tel;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.birth
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private Date birth;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.nation
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String nation;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.prov_code
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String provCode;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.city_code
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String cityCode;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.id_card
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String idCard;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.create_time
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.update_time
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.remark
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String remark;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.native_place
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String nativePlace;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.type
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String type;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.nickname
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String nickname;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.photo
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private String photo;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_user.isvalid
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	private Integer isvalid;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.user_id
	 *
	 * @return the value of t_user.user_id
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.user_id
	 *
	 * @param userId the value for t_user.user_id
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.login_tel
	 *
	 * @return the value of t_user.login_tel
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getLoginTel() {
		return loginTel;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.login_tel
	 *
	 * @param loginTel the value for t_user.login_tel
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setLoginTel(String loginTel) {
		this.loginTel = loginTel;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.login_email
	 *
	 * @return the value of t_user.login_email
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getLoginEmail() {
		return loginEmail;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.login_email
	 *
	 * @param loginEmail the value for t_user.login_email
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setLoginEmail(String loginEmail) {
		this.loginEmail = loginEmail;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.login_lq
	 *
	 * @return the value of t_user.login_lq
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getLoginLq() {
		return loginLq;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.login_lq
	 *
	 * @param loginLq the value for t_user.login_lq
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setLoginLq(String loginLq) {
		this.loginLq = loginLq;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.password
	 *
	 * @return the value of t_user.password
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.password
	 *
	 * @param password the value for t_user.password
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.salt
	 *
	 * @return the value of t_user.salt
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.salt
	 *
	 * @param salt the value for t_user.salt
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.real_name
	 *
	 * @return the value of t_user.real_name
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.real_name
	 *
	 * @param realName the value for t_user.real_name
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.sex
	 *
	 * @return the value of t_user.sex
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.sex
	 *
	 * @param sex the value for t_user.sex
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.qq
	 *
	 * @return the value of t_user.qq
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.qq
	 *
	 * @param qq the value for t_user.qq
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.email
	 *
	 * @return the value of t_user.email
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.email
	 *
	 * @param email the value for t_user.email
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.tel
	 *
	 * @return the value of t_user.tel
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.tel
	 *
	 * @param tel the value for t_user.tel
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.birth
	 *
	 * @return the value of t_user.birth
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public Date getBirth() {
		return birth;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.birth
	 *
	 * @param birth the value for t_user.birth
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setBirth(Date birth) {
		this.birth = birth;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.nation
	 *
	 * @return the value of t_user.nation
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getNation() {
		return nation;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.nation
	 *
	 * @param nation the value for t_user.nation
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setNation(String nation) {
		this.nation = nation;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.prov_code
	 *
	 * @return the value of t_user.prov_code
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getProvCode() {
		return provCode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.prov_code
	 *
	 * @param provCode the value for t_user.prov_code
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setProvCode(String provCode) {
		this.provCode = provCode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.city_code
	 *
	 * @return the value of t_user.city_code
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getCityCode() {
		return cityCode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.city_code
	 *
	 * @param cityCode the value for t_user.city_code
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.id_card
	 *
	 * @return the value of t_user.id_card
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getIdCard() {
		return idCard;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.id_card
	 *
	 * @param idCard the value for t_user.id_card
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.create_time
	 *
	 * @return the value of t_user.create_time
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.create_time
	 *
	 * @param createTime the value for t_user.create_time
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.update_time
	 *
	 * @return the value of t_user.update_time
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.update_time
	 *
	 * @param updateTime the value for t_user.update_time
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.remark
	 *
	 * @return the value of t_user.remark
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.remark
	 *
	 * @param remark the value for t_user.remark
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.native_place
	 *
	 * @return the value of t_user.native_place
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getNativePlace() {
		return nativePlace;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.native_place
	 *
	 * @param nativePlace the value for t_user.native_place
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setNativePlace(String nativePlace) {
		this.nativePlace = nativePlace;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.type
	 *
	 * @return the value of t_user.type
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.type
	 *
	 * @param type the value for t_user.type
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.nickname
	 *
	 * @return the value of t_user.nickname
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.nickname
	 *
	 * @param nickname the value for t_user.nickname
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.photo
	 *
	 * @return the value of t_user.photo
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public String getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.photo
	 *
	 * @param photo the value for t_user.photo
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setPhoto(String photo) {
		this.photo = photo;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_user.isvalid
	 *
	 * @return the value of t_user.isvalid
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public Integer getIsvalid() {
		return isvalid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_user.isvalid
	 *
	 * @param isvalid the value for t_user.isvalid
	 *
	 * @mbggenerated Fri Dec 09 17:16:58 CST 2016
	 */
	public void setIsvalid(Integer isvalid) {
		this.isvalid = isvalid;
	}

	public Integer getSsoUserid() {
		return ssoUserid;
	}

	public void setSsoUserid(Integer ssoUserid) {
		this.ssoUserid = ssoUserid;
	}

	@Override
	public String toString() {
		return "User [userId=" + userId + ", ssoUserid=" + ssoUserid + ", loginTel=" + loginTel + ", loginEmail="
				+ loginEmail + ", loginLq=" + loginLq + ", password=" + password + ", salt=" + salt + ", realName="
				+ realName + ", sex=" + sex + ", qq=" + qq + ", email=" + email + ", tel=" + tel + ", birth=" + birth
				+ ", nation=" + nation + ", provCode=" + provCode + ", cityCode=" + cityCode + ", idCard=" + idCard
				+ ", createTime=" + createTime + ", updateTime=" + updateTime + ", remark=" + remark + ", nativePlace="
				+ nativePlace + ", type=" + type + ", nickname=" + nickname + ", photo=" + photo + ", isvalid="
				+ isvalid + "]";
	}

}