package com.lanqiao.dao;

import java.util.List;
import java.util.Map;

import com.lanqiao.model.LQCity;

public interface LQCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lq_city
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int deleteByPrimaryKey(Short cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lq_city
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insert(LQCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lq_city
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insertSelective(LQCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lq_city
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    LQCity selectByPrimaryKey(Short cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lq_city
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKeySelective(LQCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lq_city
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKey(LQCity record);
    //获取省列表
      List<Map<String,Object>> findProvinces();
      
    //根据省id获取城市列表
   List<Map<String, Object>> selectByProvId(Integer cityId);
    //根据id获取city,用于显示省市汉字
    String getById(int provId);
}