package com.lanqiao.dao;

import com.lanqiao.model.StudentWeekly;

public interface StudentWeeklyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_weekly
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int deleteByPrimaryKey(Integer weekiyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_weekly
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int insert(StudentWeekly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_weekly
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int insertSelective(StudentWeekly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_weekly
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    StudentWeekly selectByPrimaryKey(Integer weekiyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_weekly
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int updateByPrimaryKeySelective(StudentWeekly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_weekly
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int updateByPrimaryKey(StudentWeekly record);
}