package com.lanqiao.dao;

import com.lanqiao.model.StudentSign;

public interface StudentSignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_sign
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int deleteByPrimaryKey(Integer signId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_sign
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int insert(StudentSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_sign
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int insertSelective(StudentSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_sign
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    StudentSign selectByPrimaryKey(Integer signId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_sign
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int updateByPrimaryKeySelective(StudentSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_sign
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int updateByPrimaryKey(StudentSign record);
}