package com.lanqiao.dao;

import com.lanqiao.model.StudentWeelyevaluate;

public interface StudentWeelyevaluateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_weelyevaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int deleteByPrimaryKey(Integer nnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_weelyevaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int insert(StudentWeelyevaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_weelyevaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int insertSelective(StudentWeelyevaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_weelyevaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    StudentWeelyevaluate selectByPrimaryKey(Integer nnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_weelyevaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int updateByPrimaryKeySelective(StudentWeelyevaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_weelyevaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int updateByPrimaryKey(StudentWeelyevaluate record);
}