package com.lanqiao.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.lanqiao.model.Student;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    Student selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKey(Student record);
    
	//学生审核状态和状态，用于抬头显示提示
	Map<String,Object> statusForHead(int studentId);
	//获取我关注的意向学员列表(我的关注)--by罗玉琳
	List<Map<String, Object>> selectMyFocusYxStuList(Map<String, Object> paramMap);
	
    //获取我关注的意向学员记录数-by罗玉琳
	Integer getMyFocusYxStuCount(Map<String, Object> paramMap);
	
	//获取全部意向学员列表(全部)--by罗玉琳
	List<Map<String, Object>> selectAllYxStuList(Map<String, Object> paramMap);
	
	//获取全部意向学员记录数-by罗玉琳
	Integer getAllYxStuCount(Map<String, Object> paramMap);
    
	//获取我关注的未分班的学员列表-by罗玉琳
	List<Map<String, Object>> selectMyFocusNoClassStuList(Map<String, Object> paramMap);
     
	//获取我关注的未分班学员记录数-by罗玉琳
	int getMyFocusNoClassStuCount(Map<String, Object> paramMap);
     
	//获取全部未分班的学员列表-by罗玉琳
	List<Map<String, Object>> selectAllNoClassStuList(Map<String, Object> paramMap);
    
	//获取全部未分班学员记录数-by罗玉琳
	int getAllNoClassStuCount(Map<String, Object> paramMap);
	
	//获取list内存在id的学员列表
	List<Map<String,Object>> getStudentByIds(List<Integer> list);
	
	//获取我关注的正式的学员列表-by罗玉琳
	List<Map<String, Object>> selectMyFocusZsStuList(Map<String, Object> paramMap);

	//获取我关注的正式学员记录数-by罗玉琳
	int getMyFocusZsStuCount(Map<String, Object> paramMap);
	
    //获取全部正式学员列表
	List<Map<String, Object>> selectAllZsStuList(Map<String, Object> paramMap);
    
	//获取全部正式学员记录数
	int getAllZsStuCount(Map<String, Object> paramMap);
	
    //获取我管理的正式学员列表
	List<Map<String, Object>> selectMyManageZsStuList(Map<String, Object> paramMap);
	
	//获取我管理的正式学员记录数
	int getMyManageZsStuCount(Map<String, Object> paramMap);
	
	//查询全部学生列表
	List<Map<String, Object>>	getAllStuExportList(Map<String, Object> paramMap);

	//查询全部学生列表
	List<Map<String, Object>>	getMyManagedStuExportList(Map<String, Object> paramMap);

	//查询全部学生列表
	List<Map<String, Object>>	getMyFocusStuExportList(Map<String, Object> paramMap);
	
    //统计当前年份已就业/在职/离职/求职中/开除/劝退/退学/延期结业/延期就业/休学重返/休学学员人数
    int getStuCount(Map<String, Object> paramMap);
    
    //统计当前年份在职/离职学员人数
    int getInOrOutWorkCount(Map<String, Object> paramMap);
    
    //我管理的就业学员人数
    int getMyManageStuJobCount(Map<String, Object> paramMap);
    
    //我管理的就业学员列表
    List<Map<String, Object>> selectMyManageStuJobList(Map<String, Object> paramMap);
    
    //全部的就业学员人数
    int getAllStuJobCount(Map<String, Object> paramMap);

    //全部的就业学员列表
    List<Map<String, Object>> selectAllStuJobList(Map<String, Object> paramMap);
    
    //我关注的就业学员人数
    int getMyFocusStuJobCount(Map<String, Object> paramMap);
    
    //我关注的就业学员列表
    List<Map<String, Object>> selectMyFocusStuJobList(Map<String, Object> paramMap);
}

