package com.lanqiao.dao;

import com.lanqiao.model.SysCourse;

public interface SysCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_course
     *
     * @mbggenerated Tue Jun 27 14:28:36 CST 2017
     */
    int deleteByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_course
     *
     * @mbggenerated Tue Jun 27 14:28:36 CST 2017
     */
    int insert(SysCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_course
     *
     * @mbggenerated Tue Jun 27 14:28:36 CST 2017
     */
    int insertSelective(SysCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_course
     *
     * @mbggenerated Tue Jun 27 14:28:36 CST 2017
     */
    SysCourse selectByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_course
     *
     * @mbggenerated Tue Jun 27 14:28:36 CST 2017
     */
    int updateByPrimaryKeySelective(SysCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_course
     *
     * @mbggenerated Tue Jun 27 14:28:36 CST 2017
     */
    int updateByPrimaryKey(SysCourse record);
}