package com.lanqiao.dao;

import java.util.List;
import java.util.Map;

import com.lanqiao.model.SysDeparment;

public interface SysDeparmentMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sys_deparment
	 *
	 * @mbggenerated Sat Nov 19 14:42:38 CST 2016
	 */
	int deleteByPrimaryKey(Integer depid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sys_deparment
	 *
	 * @mbggenerated Sat Nov 19 14:42:38 CST 2016
	 */
	int insert(SysDeparment record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sys_deparment
	 *
	 * @mbggenerated Sat Nov 19 14:42:38 CST 2016
	 */
	int insertSelective(SysDeparment record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sys_deparment
	 *
	 * @mbggenerated Sat Nov 19 14:42:38 CST 2016
	 */
	SysDeparment selectByPrimaryKey(Integer depid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sys_deparment
	 *
	 * @mbggenerated Sat Nov 19 14:42:38 CST 2016
	 */
	int updateByPrimaryKeySelective(SysDeparment record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sys_deparment
	 *
	 * @mbggenerated Sat Nov 19 14:42:38 CST 2016
	 */
	int updateByPrimaryKey(SysDeparment record);

	List<SysDeparment> selectByParentId(Integer id);

	/**
	 * 根据部门查找用户
	 * @return
	 */
	public List<Map<String, Object>> getUserByDepartment(Map<String, Object> map);

	public int getUserByDepartmentCount(Map<String, Object> map);

	/**
	 * 根据角色查找用户
	 * @return
	 */
	public List<Map<String, Object>> getUserByRole(Map<String, Object> map);

	public int getUserByRoleCount(Map<String, Object> map);

}