package com.lanqiao.dao;

import com.lanqiao.model.SysStation;

public interface SysStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_station
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int deleteByPrimaryKey(Integer stationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_station
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insert(SysStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_station
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insertSelective(SysStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_station
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    SysStation selectByPrimaryKey(Integer stationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_station
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKeySelective(SysStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_station
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKey(SysStation record);
}