package com.lanqiao.dao;

import com.lanqiao.model.SysUserRole;

public interface SysUserRoleMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sys_user_role
	 *
	 * @mbggenerated Sat Nov 19 14:42:38 CST 2016
	 */
	int deleteByPrimaryKey(Integer nnid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sys_user_role
	 *
	 * @mbggenerated Sat Nov 19 14:42:38 CST 2016
	 */
	int insert(SysUserRole record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sys_user_role
	 *
	 * @mbggenerated Sat Nov 19 14:42:38 CST 2016
	 */
	int insertSelective(SysUserRole record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sys_user_role
	 *
	 * @mbggenerated Sat Nov 19 14:42:38 CST 2016
	 */
	SysUserRole selectByPrimaryKey(Integer nnid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sys_user_role
	 *
	 * @mbggenerated Sat Nov 19 14:42:38 CST 2016
	 */
	int updateByPrimaryKeySelective(SysUserRole record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sys_user_role
	 *
	 * @mbggenerated Sat Nov 19 14:42:38 CST 2016
	 */
	int updateByPrimaryKey(SysUserRole record);

}