package com.lanqiao.dao;

import com.lanqiao.model.TClassStatusLog;

public interface TClassStatusLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_status_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int deleteByPrimaryKey(Integer classStatusLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_status_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insert(TClassStatusLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_status_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insertSelective(TClassStatusLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_status_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    TClassStatusLog selectByPrimaryKey(Integer classStatusLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_status_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKeySelective(TClassStatusLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_status_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKey(TClassStatusLog record);
}