package com.lanqiao.dao;

import com.lanqiao.model.TConsole_log;

public interface TConsole_logMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_console_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int deleteByPrimaryKey(Integer consoleLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_console_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insert(TConsole_log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_console_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insertSelective(TConsole_log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_console_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    TConsole_log selectByPrimaryKey(Integer consoleLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_console_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKeySelective(TConsole_log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_console_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKey(TConsole_log record);
}