package com.lanqiao.dao;

import com.lanqiao.model.TeacherCourseEvaluate;

public interface TeacherCourseEvaluateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course_evaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int deleteByPrimaryKey(Integer tcaeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course_evaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int insert(TeacherCourseEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course_evaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int insertSelective(TeacherCourseEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course_evaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    TeacherCourseEvaluate selectByPrimaryKey(Integer tcaeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course_evaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int updateByPrimaryKeySelective(TeacherCourseEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_course_evaluate
     *
     * @mbggenerated Tue Jun 27 14:23:02 CST 2017
     */
    int updateByPrimaryKey(TeacherCourseEvaluate record);
}