package com.lanqiao.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.lanqiao.model.TIncomeLog;

public interface TIncomeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int insert(TIncomeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int insertSelective(TIncomeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    TIncomeLog selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int updateByPrimaryKeySelective(TIncomeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int updateByPrimaryKey(TIncomeLog record);
    
    /** 费用业务获取表格数据  */
    List<Map<String,Object>> getTableData(Map<String,Object> map);

    //我管理的学费回款列表(正式学员)
    List<Map<String,Object>> getMyManageStuFeeList(Map<String,Object> paramMap);
    
    //我管理的学费回款记录数(正式学员)
    int getMyManageStuFeeCount(Map<String,Object> paramMap);
    
    //全部的学费回款列表(正式学员)
    List<Map<String,Object>> getAllStuFeeList(Map<String,Object> paramMap);
    
    //全部的学费回款列表(正式学员)
    int getAllStuFeeCount(Map<String,Object> paramMap);
    
    /** 表格数据  */
//    List<Map<String,Object>> getTableData(List<Integer> list);
    
    /** 表格数据 学费 */
//    List<Map<String,Object>> getTableDataXF(Map<String,Object> map);
    
    /** 根据userId 和 payGoal获取该条记录 */
    TIncomeLog getIncomeLogByUserIdAndType(Map<String,Object> map);
    
    /** 获取可缴费的最大金额、可减免的最大金额 */
    Long getMaxInMoney(Map<String,Object> map);
    
    /** 获取可退费的最大金额 */
    Long getMaxOutMoney(Map<String,Object> map);
    
    
}