package com.lanqiao.dao;

import java.util.List;
import java.util.Map;

import com.lanqiao.model.TJobDetail;

public interface TJobDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_detail
     *
     * @mbggenerated Mon Dec 12 17:26:21 CST 2016
     */
    int deleteByPrimaryKey(Integer jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_detail
     *
     * @mbggenerated Mon Dec 12 17:26:21 CST 2016
     */
    int insert(TJobDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_detail
     *
     * @mbggenerated Mon Dec 12 17:26:21 CST 2016
     */
    int insertSelective(TJobDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_detail
     *
     * @mbggenerated Mon Dec 12 17:26:21 CST 2016
     */
    TJobDetail selectByPrimaryKey(Integer jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_detail
     *
     * @mbggenerated Mon Dec 12 17:26:21 CST 2016
     */
    int updateByPrimaryKeySelective(TJobDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_detail
     *
     * @mbggenerated Mon Dec 12 17:26:21 CST 2016
     */
    int updateByPrimaryKey(TJobDetail record);
    
    //根据学员userId获取职业经历
	List<Map<String, Object>> getMyWorkExpByStuUserId(Integer userId);
}