package com.lanqiao.dao;

import com.lanqiao.model.TStudentclassLog;

public interface TStudentclassLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studentclass_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int deleteByPrimaryKey(Integer studentclassLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studentclass_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insert(TStudentclassLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studentclass_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insertSelective(TStudentclassLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studentclass_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    TStudentclassLog selectByPrimaryKey(Integer studentclassLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studentclass_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKeySelective(TStudentclassLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studentclass_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKey(TStudentclassLog record);
    
    /**获取对应学员id的最后一条记录*/
    Integer getLastLogByUserId(Integer stuId);
    
}