package com.lanqiao.dao;

import com.lanqiao.model.TStudentStatusLog;

public interface TStudentStatusLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_status_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int deleteByPrimaryKey(Integer studentStatusLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_status_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insert(TStudentStatusLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_status_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insertSelective(TStudentStatusLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_status_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    TStudentStatusLog selectByPrimaryKey(Integer studentStatusLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_status_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKeySelective(TStudentStatusLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_status_log
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKey(TStudentStatusLog record);
}