package com.lanqiao.dao;

import com.lanqiao.model.TStudentRemissionLog;

public interface TStudentRemissionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_remission_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int deleteByPrimaryKey(Integer studentRemissionLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_remission_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int insert(TStudentRemissionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_remission_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int insertSelective(TStudentRemissionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_remission_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    TStudentRemissionLog selectByPrimaryKey(Integer studentRemissionLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_remission_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int updateByPrimaryKeySelective(TStudentRemissionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_remission_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int updateByPrimaryKey(TStudentRemissionLog record);
}