package com.lanqiao.dao;

import com.lanqiao.model.TStudentRefundLog;

public interface TStudentRefundLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_refund_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int deleteByPrimaryKey(Integer studentRefundLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_refund_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int insert(TStudentRefundLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_refund_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int insertSelective(TStudentRefundLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_refund_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    TStudentRefundLog selectByPrimaryKey(Integer studentRefundLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_refund_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int updateByPrimaryKeySelective(TStudentRefundLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_refund_log
     *
     * @mbggenerated Mon Dec 12 12:08:33 CST 2016
     */
    int updateByPrimaryKey(TStudentRefundLog record);
}