package com.lanqiao.dao;

import com.lanqiao.model.TUserDataAuth;

public interface TUserDataAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_data_auth
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int deleteByPrimaryKey(Integer userDataAnthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_data_auth
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insert(TUserDataAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_data_auth
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int insertSelective(TUserDataAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_data_auth
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    TUserDataAuth selectByPrimaryKey(Integer userDataAnthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_data_auth
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKeySelective(TUserDataAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_data_auth
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TUserDataAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_data_auth
     *
     * @mbggenerated Sat Nov 19 14:42:38 CST 2016
     */
    int updateByPrimaryKey(TUserDataAuth record);
}