package com.lanqiao.dao;

import com.lanqiao.model.TVisitSubLog;

public interface TVisitSubLogMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_visit_sub_log
	 *
	 * @mbggenerated Fri Nov 25 17:49:36 CST 2016
	 */
	int deleteByPrimaryKey(Integer nnid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_visit_sub_log
	 *
	 * @mbggenerated Fri Nov 25 17:49:36 CST 2016
	 */
	int insert(TVisitSubLog record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_visit_sub_log
	 *
	 * @mbggenerated Fri Nov 25 17:49:36 CST 2016
	 */
	int insertSelective(TVisitSubLog record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_visit_sub_log
	 *
	 * @mbggenerated Fri Nov 25 17:49:36 CST 2016
	 */
	TVisitSubLog selectByPrimaryKey(Integer nnid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_visit_sub_log
	 *
	 * @mbggenerated Fri Nov 25 17:49:36 CST 2016
	 */
	int updateByPrimaryKeySelective(TVisitSubLog record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_visit_sub_log
	 *
	 * @mbggenerated Fri Nov 25 17:49:36 CST 2016
	 */
	int updateByPrimaryKey(TVisitSubLog record);

	int deleteByvisitId(Integer visitId);
}